mxGraph: com.mxgraph.mxCell Class Reference
com.mxgraph.mxCell Class Reference
Cells are the elements of the graph model. They represent the state of the groups, vertices and edges in a graph.
Public Member Functions
mxCell ()
Constructs a new empty cell.
mxCell (Object value)
Constructs a new cell for the given value.
mxCell (Object value, mxGeometry geometry, string style)
Constructs a new cell for the given value, geometry and style.
mxICell GetTerminal (bool source)
Returns the source or target terminal of the cell.
mxICell SetTerminal (mxICell terminal, bool isSource)
Sets the source or target terminal.
int ChildCount ()
Returns the number of child cells.
int GetIndex (mxICell child)
Returns the index of the specified child in the child array.
mxICell GetChildAt (int index)
Returns the child at the specified index.
mxICell Insert (mxICell child)
Appends the specified child into the child array and updates the parent reference of the child.
mxICell Insert (mxICell child, int index)
Inserts the specified child into the child array at the specified index and updates the parent reference of the child.
mxICell Remove (int index)
Removes the child at the specified index from the child array and returns the child that was removed. Will remove the parent reference of the child.
mxICell Remove (mxICell child)
Removes the given child from the child array. Will remove the parent reference of the child.
void RemoveFromParent ()
Removes the cell from its parent.
int EdgeCount ()
Returns the number of edges in the edge array.
int GetEdgeIndex (mxICell edge)
Returns the index of the specified edge in the edge array.
mxICell GetEdgeAt (int index)
Returns the edge at the specified index in the edge array.
mxICell InsertEdge (mxICell edge, bool isOutgoing)
Inserts the specified edge into the edge array and returns the edge. Will update the respective terminal reference of the edge.
mxICell RemoveEdge (mxICell edge, bool isOutgoing)
Removes the specified edge from the edge array and returns the edge. Will remove the respective terminal reference from the edge.
void RemoveFromTerminal (bool isSource)
Removes the edge from its source or target terminal.
String GetAttribute (String name)
Returns the specified attribute from the user object if it is an XML
String GetAttribute (String name, String defaultValue)
Returns the specified attribute from the user object if it is an XML
void SetAttribute (String name, String value)
Object Clone ()
Returns a clone of this cell.
Protected Attributes
string id
Holds the Id. Default is null.
Object value
Holds the user object. Default is null.
mxGeometry geometry
Holds the geometry. Default is null.
string style
Holds the geometry. Default is null.
bool vertex = false
Specifies whether the cell is a vertex. Default value is false.
bool edge = false
Specifies whether the cell is an edge. Default value is false.
bool connectable = true
Specifies whether the cell connectable. Default value is true.
bool visible = true
Specifies whether the cell is visible. Default value is true.
bool collapsed = false
Specifies whether the cell is collapsed. Default value is false.
mxICell parent
Reference to the parent cell.
mxICell source
Reference to the source terminal of an edge.
mxICell target
Reference to the target terminal of an edge.
List< mxICell > children
Holds the child cells.
List< mxICell > edges
Holds the connected edges.
Properties
string Id [get, set]
Object Value [get, set]
mxGeometry Geometry [get, set]
string Style [get, set]
bool Vertex [get, set]
bool Edge [get, set]
bool Connectable [get, set]
bool Visible [get, set]
bool Collapsed [get, set]
mxICell Parent [get, set]
mxICell Source [get, set]
Sets or returns the source terminal of the cell.
mxICell Target [get, set]
Sets or returns the target terminal of the cell.
Properties inherited from com.mxgraph.mxICell
string Id [get, set]
Sets or returns the Id of the cell.
Object Value [get, set]
Sets or returns the user object of the cell.
mxGeometry Geometry [get, set]
Sets or returns the geometry of the cell.
string Style [get, set]
Sets or returns the string that describes the style.
bool Vertex [get]
Returns true if the cell is a vertex.
bool Edge [get]
Returns true if the cell is an edge.
bool Connectable [get]
Returns true if the cell is connectable.
bool Visible [get, set]
Sets or returns the visible state of the cell.
bool Collapsed [get, set]
Sets or returns the collapsed state of the cell.
mxICell Parent [get, set]
Sets or returns the parent of the cell.
Detailed Description
Cells are the elements of the graph model. They represent the state of the groups, vertices and edges in a graph.
Constructor & Destructor Documentation
mxCell() [1/3]
com.mxgraph.mxCell.mxCell () inline
Constructs a new empty cell.
mxCell() [2/3]
com.mxgraph.mxCell.mxCell (Object value) inline
Constructs a new cell for the given value.
Parameters
value Value that represents the user object.
mxCell() [3/3]
com.mxgraph.mxCell.mxCell (Object value, mxGeometry geometry, string style) inline
Constructs a new cell for the given value, geometry and style.
Parameters
value Value that represents the user object.
geometry Geometry of the cell to be created.
style Style of the cell to be created.
Member Function Documentation
ChildCount()
int com.mxgraph.mxCell.ChildCount () inline
Returns the number of child cells.
Returns
Returns the number of child cells.
Implements com.mxgraph.mxICell.
Clone()
Object com.mxgraph.mxCell.Clone () inline
Returns a clone of this cell.
Returns
Returns a clone of this cell.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxGeometry.Clone().
EdgeCount()
int com.mxgraph.mxCell.EdgeCount () inline
Returns the number of edges in the edge array.
Returns
Returns the number of edges.
Implements com.mxgraph.mxICell.
GetAttribute() [1/2]
String com.mxgraph.mxCell.GetAttribute (String name) inline
Returns the specified attribute from the user object if it is an XML
node.
Parameters
name Name of the attribute whose value should be returned.
Returns
Returns the value of the given attribute or null.
GetAttribute() [2/2]
String com.mxgraph.mxCell.GetAttribute (String name, String defaultValue) inline
Returns the specified attribute from the user object if it is an XML
node.
Parameters
name Name of the attribute whose value should be returned.
defaultValue Default value to use if the attribute has no value.
Returns
Returns the value of the given attribute or defaultValue.
GetChildAt()
mxICell com.mxgraph.mxCell.GetChildAt (int index) inline
Returns the child at the specified index.
Parameters
index Integer that specifies the child to be returned.
Returns
Returns the child at the specified index.
Implements com.mxgraph.mxICell.
GetEdgeAt()
mxICell com.mxgraph.mxCell.GetEdgeAt (int index) inline
Returns the edge at the specified index in the edge array.
Parameters
index Integer that specifies the index of the edge to be returned.
Returns
Returns the edge at the specified index.
Implements com.mxgraph.mxICell.
GetEdgeIndex()
int com.mxgraph.mxCell.GetEdgeIndex (mxICell edge) inline
Returns the index of the specified edge in the edge array.
Parameters
edge Cell whose index should be returned.
Returns
Returns the index of the given edge.
Implements com.mxgraph.mxICell.
GetIndex()
int com.mxgraph.mxCell.GetIndex (mxICell child) inline
Returns the index of the specified child in the child array.
Parameters
child Child whose index should be returned.
Returns
Returns the index of the specified child.
Implements com.mxgraph.mxICell.
GetTerminal()
mxICell com.mxgraph.mxCell.GetTerminal (bool source) inline
Returns the source or target terminal of the cell.
Parameters
source Boolean that specifies if the source terminal should be returned.
Returns
Returns the source or target terminal.
Implements com.mxgraph.mxICell.
Insert() [1/2]
mxICell com.mxgraph.mxCell.Insert (mxICell child) inline
Appends the specified child into the child array and updates the parent reference of the child.
Parameters
child Cell to be appended to the child array.
Returns
Returns the appended child.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.Parent.
Referenced by com.mxgraph.mxGraphModel.CreateRoot().
Insert() [2/2]
mxICell com.mxgraph.mxCell.Insert (mxICell child, int index) inline
Inserts the specified child into the child array at the specified index and updates the parent reference of the child.
Parameters
child Cell to be inserted into the child array.
index Integer that specifies the index at which the child should be inserted into the child array.
Returns
Returns the inserted child.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.Insert(), com.mxgraph.mxICell.Parent, and com.mxgraph.mxICell.RemoveFromParent().
InsertEdge()
mxICell com.mxgraph.mxCell.InsertEdge (mxICell edge, bool isOutgoing) inline
Inserts the specified edge into the edge array and returns the edge. Will update the respective terminal reference of the edge.
Parameters
edge Cell to be inserted into the edge array.
isOutgoing Boolean that specifies if the edge is outgoing.
Returns
Returns the inserted edge.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.GetTerminal(), com.mxgraph.mxICell.RemoveFromTerminal(), and com.mxgraph.mxICell.SetTerminal().
Remove() [1/2]
mxICell com.mxgraph.mxCell.Remove (int index) inline
Removes the child at the specified index from the child array and returns the child that was removed. Will remove the parent reference of the child.
Parameters
index Integer that specifies the index of the child to be removed.
Returns
Returns the child that was removed.
Implements com.mxgraph.mxICell.
Remove() [2/2]
mxICell com.mxgraph.mxCell.Remove (mxICell child) inline
Removes the given child from the child array. Will remove the parent reference of the child.
Parameters
child
Returns
Returns the child that was removed.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.Parent, and com.mxgraph.mxICell.Remove().
RemoveEdge()
mxICell com.mxgraph.mxCell.RemoveEdge (mxICell edge, bool isOutgoing) inline
Removes the specified edge from the edge array and returns the edge. Will remove the respective terminal reference from the edge.
Parameters
edge Cell to be removed from the edge array.
isOutgoing Boolean that specifies if the edge is outgoing.
Returns
Returns the edge that was removed.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.GetTerminal(), com.mxgraph.mxICell.Remove(), and com.mxgraph.mxICell.SetTerminal().
RemoveFromParent()
void com.mxgraph.mxCell.RemoveFromParent () inline
Removes the cell from its parent.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.Remove().
RemoveFromTerminal()
void com.mxgraph.mxCell.RemoveFromTerminal (bool isSource) inline
Removes the edge from its source or target terminal.
Parameters
isSource Boolean that specifies if the edge should be removed from its source or target terminal.
Implements com.mxgraph.mxICell.
References com.mxgraph.mxICell.RemoveEdge().
SetAttribute()
void com.mxgraph.mxCell.SetAttribute (String name, String value) inline
Sets the specified attribute on the user object if it is an XML node.
Parameters
name Name of the attribute whose value should be set.
value New value of the attribute.
SetTerminal()
mxICell com.mxgraph.mxCell.SetTerminal (mxICell terminal, bool source) inline
Sets the source or target terminal.
Parameters
terminal Cell that represents the new source or target terminal.
source Boolean that specifies if the source or target terminal should be set.
Returns
Returns the new terminal.
Implements com.mxgraph.mxICell.
Member Data Documentation
children
List<mxICell> com.mxgraph.mxCell.children protected
Holds the child cells.
collapsed
bool com.mxgraph.mxCell.collapsed = false protected
Specifies whether the cell is collapsed. Default value is false.
connectable
bool com.mxgraph.mxCell.connectable = true protected
Specifies whether the cell connectable. Default value is true.
edge
bool com.mxgraph.mxCell.edge = false protected
Specifies whether the cell is an edge. Default value is false.
edges
List<mxICell> com.mxgraph.mxCell.edges protected
Holds the connected edges.
geometry
mxGeometry com.mxgraph.mxCell.geometry protected
Holds the geometry. Default is null.
id
string com.mxgraph.mxCell.id protected
Holds the Id. Default is null.
parent
mxICell com.mxgraph.mxCell.parent protected
Reference to the parent cell.
source
mxICell com.mxgraph.mxCell.source protected
Reference to the source terminal of an edge.
style
string com.mxgraph.mxCell.style protected
Holds the geometry. Default is null.
target
mxICell com.mxgraph.mxCell.target protected
Reference to the target terminal of an edge.
value
Object com.mxgraph.mxCell.value protected
Holds the user object. Default is null.
vertex
bool com.mxgraph.mxCell.vertex = false protected
Specifies whether the cell is a vertex. Default value is false.
visible
bool com.mxgraph.mxCell.visible = true protected
Specifies whether the cell is visible. Default value is true.
Property Documentation
Source
mxICell com.mxgraph.mxCell.Source get set
Sets or returns the source terminal of the cell.
Target
mxICell com.mxgraph.mxCell.Target get set
Sets or returns the target terminal of the cell.
The documentation for this class was generated from the following file:
src/model/mxCell.cs