mxGraph: com.mxgraph.mxCellPath Class Reference
com.mxgraph.mxCellPath Class Reference
Implements a mechanism for temporary cell Ids.
Static Public Member Functions
static string Create (mxICell cell)
Creates the cell path for the given cell. The cell path is a concatenation of the indices of all cells on the (finite) path to the root, eg. "0.0.0.1".
static string GetParentPath (string path)
Returns the path for the parent of the cell represented by the given path. Returns null if the given path has no parent.
static mxICell Resolve (mxICell root, string path)
Returns the cell for the specified cell path using the given root as the root of the path.
Static Public Attributes
static char PATH_SEPARATOR = '.'
Defines the separator between the path components. Default is ".".
Detailed Description
Implements a mechanism for temporary cell Ids.
Member Function Documentation
Create()
static string com.mxgraph.mxCellPath.Create (mxICell cell) inline static
Creates the cell path for the given cell. The cell path is a concatenation of the indices of all cells on the (finite) path to the root, eg. "0.0.0.1".
Parameters
cell Cell whose path should be returned.
Returns
Returns the string that represents the path.
References com.mxgraph.mxICell.GetIndex(), com.mxgraph.mxICell.Parent, and com.mxgraph.mxCellPath.PATH_SEPARATOR.
Referenced by com.mxgraph.mxCodec.GetId(), and com.mxgraph.mxGraphModel.GetNearestCommonAncestor().
GetParentPath()
static string com.mxgraph.mxCellPath.GetParentPath (string path) inline static
Returns the path for the parent of the cell represented by the given path. Returns null if the given path has no parent.
Parameters
path Path whose parent path should be returned.
References com.mxgraph.mxCellPath.PATH_SEPARATOR.
Referenced by com.mxgraph.mxGraphModel.GetNearestCommonAncestor().
Resolve()
static mxICell com.mxgraph.mxCellPath.Resolve (mxICell root, string path) inline static
Returns the cell for the specified cell path using the given root as the root of the path.
Parameters
root Root cell of the path to be resolved.
path String that defines the path.
Returns
Returns the cell that is defined by the path.
References com.mxgraph.mxICell.GetChildAt().
Member Data Documentation
PATH_SEPARATOR
char com.mxgraph.mxCellPath.PATH_SEPARATOR = '.' static
Defines the separator between the path components. Default is ".".
Referenced by com.mxgraph.mxCellPath.Create(), com.mxgraph.mxGraphModel.GetNearestCommonAncestor(), and com.mxgraph.mxCellPath.GetParentPath().
The documentation for this class was generated from the following file:
src/model/mxCellPath.cs