mxGraph: com.mxgraph.mxGraphViewReader Class Reference
com.mxgraph.mxGraphViewReader Class Reference abstract
An abstract converter that renders display XML data onto a canvas.
Public Member Functions
mxGraphViewReader ()
Constructs a new graph view reader.
mxGraphViewReader (XmlReader reader)
Constructs a new graph view reader and reads the given display XML data.
abstract mxICanvas CreateCanvas (Dictionary< string, Object > attrs)
Returns the canvas to be used for rendering.
void Read (XmlReader reader)
Reads the given display XML data and parses all elements.
void ParseElement (string tagName, Dictionary< string, Object > attrs)
Parses the given element and paints it onto the canvas.
string ParseState (mxCellState state, bool edge)
Parses the bounds, absolute points and label information from the style of the state into its respective fields and returns the label of the cell.
Static Public Member Functions
static List< mxPoint > ParsePoints (string pts)
Parses the list of points into an object-oriented representation.
Protected Attributes
mxICanvas canvas
Holds the canvas to be used for rendering the graph.
double scale = 1
Holds the global scale of the graph. This is set just before createCanvas is called.
Properties
mxICanvas Canvas [get]
Returns the canvas that is used for rendering the graph.
Detailed Description
An abstract converter that renders display XML data onto a canvas.
Constructor & Destructor Documentation
mxGraphViewReader() [1/2]
com.mxgraph.mxGraphViewReader.mxGraphViewReader () inline
Constructs a new graph view reader.
mxGraphViewReader() [2/2]
com.mxgraph.mxGraphViewReader.mxGraphViewReader (XmlReader reader) inline
Constructs a new graph view reader and reads the given display XML data.
Parameters
reader Reader that represents the display XML data.
Member Function Documentation
CreateCanvas()
abstract mxICanvas com.mxgraph.mxGraphViewReader.CreateCanvas (Dictionary< string, Object > attrs) pure virtual
Returns the canvas to be used for rendering.
Parameters
attrs Specifies the attributes of the new canvas.
Returns
Returns a new canvas.
Implemented in com.mxgraph.mxGraphViewImageReader.
ParseElement()
void com.mxgraph.mxGraphViewReader.ParseElement (string tagName, Dictionary< string, Object > attrs) inline
Parses the given element and paints it onto the canvas.
Parameters
tagName Name of the node to be parsed.
attrs Attributes of the node to be parsed.
References com.mxgraph.mxICanvas.DrawCell(), com.mxgraph.mxICanvas.DrawLabel(), com.mxgraph.mxUtils.GetDouble(), and com.mxgraph.mxICanvas.Scale.
ParsePoints()
static List<mxPoint> com.mxgraph.mxGraphViewReader.ParsePoints (string pts) inline static
Parses the list of points into an object-oriented representation.
Parameters
pts String containing a list of points.
Returns
Returns the points as a list of mxPoints.
ParseState()
string com.mxgraph.mxGraphViewReader.ParseState (mxCellState state, bool edge) inline
Parses the bounds, absolute points and label information from the style of the state into its respective fields and returns the label of the cell.
References com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxUtils.GetLabelPaintBounds(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxCellState.LabelBounds, com.mxgraph.mxCellState.Style, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Read()
void com.mxgraph.mxGraphViewReader.Read (XmlReader reader) inline
Reads the given display XML data and parses all elements.
Parameters
reader Reader that represents the display XML data.
Member Data Documentation
canvas
mxICanvas com.mxgraph.mxGraphViewReader.canvas protected
Holds the canvas to be used for rendering the graph.
scale
double com.mxgraph.mxGraphViewReader.scale = 1 protected
Holds the global scale of the graph. This is set just before createCanvas is called.
Property Documentation
Canvas
mxICanvas com.mxgraph.mxGraphViewReader.Canvas get
Returns the canvas that is used for rendering the graph.
Referenced by com.mxgraph.mxGraphViewImageReader.Convert().
The documentation for this class was generated from the following file:
src/reader/mxGraphViewReader.cs