mxGraph: com.mxgraph.mxGraphView Class Reference
com.mxgraph.mxGraphView Class Reference
Implements a view for the graph. This class is in charge of computing the absolute coordinates for the relative child geometries, the points for perimeters and edge styles and keeping them cached in mxCellStates for faster retrieval. The states are updated whenever the model or the view state (translate, scale) changes. The scale and translate are honoured in the bounds.
Public Member Functions
mxGraphView (mxGraph graph)
Constructs a new view for the given graph.
mxRectangle GetBounds (Object[] cells)
Returns the bounding box for an array of cells or null, if no cells are specified.
mxRectangle GetBoundingBox (Object[] cells)
Returns the bounding box for an array of cells or null, if no cells are specified.
mxRectangle GetBounds (Object[] cells, bool boundingBox)
Returns the bounding box for an array of cells or null, if no cells are specified.
void Revalidate ()
First invalidates, then validates all cell states.
void Invalidate ()
Invalidates all cell states.
void Validate ()
First validates all bounds and then validates all points recursively on all visible cells.
mxRectangle GetBoundingBox (mxCellState state)
Shortcut to validateCell with visible set to true.
mxRectangle GetBoundingBox (mxCellState state, Boolean recurse)
Returns the bounding box of the shape and the label for the given cell state and its children if recurse is true.
Object ValidateCell (Object cell)
Shortcut to validateCell with visible set to true.
Object ValidateCell (Object cell, Boolean visible)
Recursively creates the cell state for the given cell if visible is true and the given cell is visible. If the cell is not visible but the state exists then it is removed using removeState.
mxCellState ValidateCellState (Object cell)
Shortcut to validateCellState with recurse set to true.
mxCellState ValidateCellState (Object cell, Boolean recurse)
Validates the cell state for the given cell.
void UpdateCellState (mxCellState state, mxCellState source, mxCellState target)
Updates the given cell state.
void UpdateVertexState (mxCellState state, mxGeometry geo)
Validates the given cell state.
void UpdateEdgeState (mxCellState state, mxGeometry geo, mxCellState source, mxCellState target)
Validates the given cell state.
void UpdateVertexLabelOffset (mxCellState state)
Updates the absoluteOffset of the given vertex cell state. This takes into account the label position styles.
void UpdateLabelBounds (mxCellState state)
Updates the label bounds in the given state.
mxRectangle UpdateBoundingBox (mxCellState state)
Updates the bounding box in the given cell state.
void UpdateFixedTerminalPoints (mxCellState edge, mxCellState source, mxCellState target)
Sets the initial absolute terminal points in the given state before the edge style is computed.
void UpdateFixedTerminalPoint (mxCellState edge, mxCellState terminal, bool source, mxConnectionConstraint constraint)
Sets the fixed source or target terminal point on the given edge.
void UpdatePoints (mxCellState edge, List< mxPoint > points, mxCellState source, mxCellState target)
Updates the absolute points in the given state using the specified array of points as the relative points.
mxPoint TransformControlPoint (mxCellState state, mxPoint pt)
Transforms the given control point to an absolute point.
mxEdgeStyleFunction GetEdgeStyle (mxCellState edge, List< mxPoint > points, Object source, Object target)
Returns the edge style function to be used to render the given edge state.
void UpdateFloatingTerminalPoints (mxCellState state, mxCellState source, mxCellState target)
Updates the terminal points in the given state after the edge style was computed for the edge.
void UpdateFloatingTerminalPoint (mxCellState edge, mxCellState start, mxCellState end, bool source)
Updates the absolute terminal point in the given state for the given start and end state, where start is the source if source is true.
mxCellState GetTerminalPort (mxCellState state, mxCellState terminal, bool source)
Returns the given terminal or the port defined in the given edge state if a cell state exists for that port.
mxPoint GetPerimeterPoint (mxCellState terminal, mxPoint next, bool orthogonal)
Returns a point that defines the location of the intersection point between the perimeter and the line between the center of the shape and the given point.
mxPoint GetPerimeterPoint (mxCellState terminal, mxPoint next, bool orthogonal, double border)
Returns a point that defines the location of the intersection point between the perimeter and the line between the center of the shape and the given point.
double GetRoutingCenterX (mxCellState state)
Returns the x-coordinate of the center point for automatic routing.
double GetRoutingCenterY (mxCellState state)
Returns the y-coordinate of the center point for automatic routing.
mxRectangle GetPerimeterBounds (mxCellState terminal, double border)
Returns the perimeter bounds for the given terminal, edge pair.
mxPerimeterFunction GetPerimeterFunction (mxCellState state)
Returns the perimeter function for the given state.
mxPoint GetNextPoint (mxCellState edge, mxCellState opposite, bool source)
Returns the nearest point in the list of absolute points or the center of the opposite terminal.
Object GetVisibleTerminal (Object edge, bool source)
Returns the nearest ancestor terminal that is visible. The edge appears to be connected to this terminal on the display.
void UpdateEdgeBounds (mxCellState state)
Updates the given state using the bounding box of the absolute points. Also updates terminal distance, length and segments.
mxPoint GetPoint (mxCellState state)
Returns the absolute center point along the given edge.
mxPoint GetPoint (mxCellState state, mxGeometry geometry)
Returns the absolute point on the edge for the given relative geometry as a point. The edge is represented by the given cell state.
mxCellState GetState (Object cell)
Returns the state for the given cell or null if no state is defined for the cell.
Dictionary< Object, mxCellState > GetStates (Object[] cells)
Returns the object that maps from cells to states.
mxCellState [] GetCellStates (Object[] cells)
Returns the states for the given array of cells. The array contains all states that are not null, that is, the returned array may have less elements than the given array.
mxCellState GetState (Object cell, bool create)
Returns the cell state for the given cell. If create is true, then the state is created if it does not yet exist.
mxCellState RemoveState (Object cell)
Shortcut to removeState with recurse set to false.
mxCellState RemoveState (Object cell, Boolean recurse)
Removes and returns the mxCellState for the given cell.
mxCellState CreateState (Object cell)
Creates and returns a cell state for the given cell.
Protected Attributes
mxGraph graph
Reference to the enclosing graph.
mxRectangle graphBounds = new mxRectangle()
Caches the current bounds of the graph.
double scale = 1
Specifies the scale. Default is 1 (100%).
mxPoint translate = new mxPoint(0, 0)
Point that specifies the current translation. Default is a new empty point.
Dictionary< Object, mxCellState > states = new Dictionary<Object, mxCellState>()
Maps from cells to cell states.
bool eventsEnabled = true
Specifies if the view should be revalidated if the scale or translation changes.
Properties
mxGraph Graph [get]
Returns the enclosing graph.
mxRectangle GraphBounds [get, set]
Returns the cached diagram bounds.
double Scale [get, set]
Sets or returns the current scale.
mxPoint Translate [get, set]
Sets or returns the current translation.
Dictionary< Object, mxCellState > States [get, set]
Sets or returns the current translation.
bool IsEventsEnabled [get, set]
Sets or returns the current scale.
Detailed Description
Implements a view for the graph. This class is in charge of computing the absolute coordinates for the relative child geometries, the points for perimeters and edge styles and keeping them cached in mxCellStates for faster retrieval. The states are updated whenever the model or the view state (translate, scale) changes. The scale and translate are honoured in the bounds.
Constructor & Destructor Documentation
mxGraphView()
com.mxgraph.mxGraphView.mxGraphView (mxGraph graph) inline
Constructs a new view for the given graph.
Parameters
graph Reference to the enclosing graph.
Member Function Documentation
CreateState()
mxCellState com.mxgraph.mxGraphView.CreateState (Object cell) inline
Creates and returns a cell state for the given cell.
Parameters
cell Cell for which a new state should be created.
Returns
Returns a new state for the given cell.
References com.mxgraph.mxGraph.GetCellStyle().
GetBoundingBox() [1/3]
mxRectangle com.mxgraph.mxGraphView.GetBoundingBox (Object [] cells) inline
Returns the bounding box for an array of cells or null, if no cells are specified.
Parameters
cells
Returns
GetBoundingBox() [2/3]
mxRectangle com.mxgraph.mxGraphView.GetBoundingBox (mxCellState state) inline
Shortcut to validateCell with visible set to true.
GetBoundingBox() [3/3]
mxRectangle com.mxgraph.mxGraphView.GetBoundingBox (mxCellState state, Boolean recurse) inline
Returns the bounding box of the shape and the label for the given cell state and its children if recurse is true.
Parameters
state Cell state whose bounding box should be returned.
recurse Boolean indicating if the children should be included.
References com.mxgraph.mxRectangle.Add(), com.mxgraph.mxCellState.BoundingBox, com.mxgraph.mxCellState.Cell, com.mxgraph.mxRectangle.Clone(), com.mxgraph.mxIGraphModel.GetChildAt(), com.mxgraph.mxIGraphModel.GetChildCount(), and com.mxgraph.mxGraph.Model.
GetBounds() [1/2]
mxRectangle com.mxgraph.mxGraphView.GetBounds (Object [] cells) inline
Returns the bounding box for an array of cells or null, if no cells are specified.
Parameters
cells
Returns
Referenced by com.mxgraph.mxGraph.GetCellBounds().
GetBounds() [2/2]
mxRectangle com.mxgraph.mxGraphView.GetBounds (Object [] cells, bool boundingBox) inline
Returns the bounding box for an array of cells or null, if no cells are specified.
References com.mxgraph.mxRectangle.Add(), com.mxgraph.mxCellState.BoundingBox, com.mxgraph.mxIGraphModel.IsEdge(), com.mxgraph.mxIGraphModel.IsVertex(), and com.mxgraph.mxGraph.Model.
GetCellStates()
mxCellState [] com.mxgraph.mxGraphView.GetCellStates (Object [] cells) inline
Returns the states for the given array of cells. The array contains all states that are not null, that is, the returned array may have less elements than the given array.
GetEdgeStyle()
mxEdgeStyleFunction com.mxgraph.mxGraphView.GetEdgeStyle (mxCellState edge, List< mxPoint > points, Object source, Object target) inline
Returns the edge style function to be used to render the given edge state.
References com.mxgraph.mxGraph.DefaultLoopStyle, com.mxgraph.mxUtils.Eval(), com.mxgraph.mxStyleRegistry.GetValue(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxEdgeStyleFunction(), com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_EDGE, com.mxgraph.mxConstants.STYLE_LOOP, and com.mxgraph.mxConstants.STYLE_NOEDGESTYLE.
Referenced by com.mxgraph.mxGraph.IsOrthogonal().
GetNextPoint()
mxPoint com.mxgraph.mxGraphView.GetNextPoint (mxCellState edge, mxCellState opposite, bool source) inline
Returns the nearest point in the list of absolute points or the center of the opposite terminal.
Parameters
edge State that represents the edge.
opposite State that represents the opposite terminal.
source Boolean indicating if the next point for the source or target should be returned.
References com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxRectangle.GetCenterX(), and com.mxgraph.mxRectangle.GetCenterY().
GetPerimeterBounds()
mxRectangle com.mxgraph.mxGraphView.GetPerimeterBounds (mxCellState terminal, double border) inline
Returns the perimeter bounds for the given terminal, edge pair.
References com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxCellState.GetPerimeterBounds(), com.mxgraph.mxCellState.Style, and com.mxgraph.mxConstants.STYLE_PERIMETER_SPACING.
GetPerimeterFunction()
mxPerimeterFunction com.mxgraph.mxGraphView.GetPerimeterFunction (mxCellState state) inline
Returns the perimeter function for the given state.
References com.mxgraph.mxUtils.Eval(), com.mxgraph.mxStyleRegistry.GetValue(), com.mxgraph.mxPerimeterFunction(), com.mxgraph.mxCellState.Style, and com.mxgraph.mxConstants.STYLE_PERIMETER.
GetPerimeterPoint() [1/2]
mxPoint com.mxgraph.mxGraphView.GetPerimeterPoint (mxCellState terminal, mxPoint next, bool orthogonal) inline
Returns a point that defines the location of the intersection point between the perimeter and the line between the center of the shape and the given point.
GetPerimeterPoint() [2/2]
mxPoint com.mxgraph.mxGraphView.GetPerimeterPoint (mxCellState terminal, mxPoint next, bool orthogonal, double border) inline
Returns a point that defines the location of the intersection point between the perimeter and the line between the center of the shape and the given point.
Parameters
terminal State for the source or target terminal.
next Point that lies outside of the given terminal.
orthogonal Specifies if the orthogonal projection onto the perimeter should be returned. If this is false then the intersection of the perimeter and the line between the next and the center point is returned.
border Optional border between the perimeter and the shape.
References com.mxgraph.mxRectangle.Height, com.mxgraph.mxPerimeterFunction(), and com.mxgraph.mxRectangle.Width.
GetPoint() [1/2]
mxPoint com.mxgraph.mxGraphView.GetPoint (mxCellState state) inline
Returns the absolute center point along the given edge.
GetPoint() [2/2]
mxPoint com.mxgraph.mxGraphView.GetPoint (mxCellState state, mxGeometry geometry) inline
Returns the absolute point on the edge for the given relative geometry as a point. The edge is represented by the given cell state.
Parameters
state Represents the state of the parent edge.
geometry Represents the relative location.
References com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxRectangle.GetCenterX(), com.mxgraph.mxRectangle.GetCenterY(), com.mxgraph.mxCellState.Length, com.mxgraph.mxGeometry.Offset, com.mxgraph.mxGeometry.Relative, com.mxgraph.mxCellState.Segments, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
GetRoutingCenterX()
double com.mxgraph.mxGraphView.GetRoutingCenterX (mxCellState state) inline
Returns the x-coordinate of the center point for automatic routing.
Returns
Returns the x-coordinate of the routing center point.
References com.mxgraph.mxRectangle.GetCenterX(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_ROUTING_CENTER_X, and com.mxgraph.mxRectangle.Width.
GetRoutingCenterY()
double com.mxgraph.mxGraphView.GetRoutingCenterY (mxCellState state) inline
Returns the y-coordinate of the center point for automatic routing.
Returns
Returns the y-coordinate of the routing center point.
References com.mxgraph.mxRectangle.GetCenterY(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxCellState.Style, and com.mxgraph.mxConstants.STYLE_ROUTING_CENTER_Y.
GetState() [1/2]
mxCellState com.mxgraph.mxGraphView.GetState (Object cell) inline
Returns the state for the given cell or null if no state is defined for the cell.
Parameters
cell Cell whose state should be returned.
Returns
Returns the state for the given cell.
Referenced by com.mxgraph.mxGraph.DrawCell(), com.mxgraph.mxGraph.GetCellAt(), and com.mxgraph.mxGraph.HitsSwimlaneContent().
GetState() [2/2]
mxCellState com.mxgraph.mxGraphView.GetState (Object cell, bool create) inline
Returns the cell state for the given cell. If create is true, then the state is created if it does not yet exist.
Parameters
cell Cell for which a new state should be returned.
create Boolean indicating if a new state should be created if it does not yet exist.
Returns
Returns the state for the given cell.
References com.mxgraph.mxGraph.IsCellVisible().
GetStates()
Dictionary<Object, mxCellState> com.mxgraph.mxGraphView.GetStates (Object [] cells) inline
Returns the object that maps from cells to states.
GetTerminalPort()
mxCellState com.mxgraph.mxGraphView.GetTerminalPort (mxCellState state, mxCellState terminal, bool source) inline
Returns the given terminal or the port defined in the given edge state if a cell state exists for that port.
References com.mxgraph.mxUtils.GetString(), com.mxgraph.mxGraph.Model, com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_SOURCE_PORT, and com.mxgraph.mxConstants.STYLE_TARGET_PORT.
GetVisibleTerminal()
Object com.mxgraph.mxGraphView.GetVisibleTerminal (Object edge, bool source) inline
Returns the nearest ancestor terminal that is visible. The edge appears to be connected to this terminal on the display.
Parameters
edge Cell whose visible terminal should be returned.
source Boolean that specifies if the source or target terminal should be returned.
Returns
Returns the visible source or target terminal.
References com.mxgraph.mxIGraphModel.GetParent(), com.mxgraph.mxIGraphModel.GetTerminal(), com.mxgraph.mxGraph.IsCellCollapsed(), com.mxgraph.mxGraph.IsCellVisible(), com.mxgraph.mxGraph.Model, and com.mxgraph.mxIGraphModel.Root.
Referenced by com.mxgraph.mxGraph.FindTreeRoots(), com.mxgraph.mxGraph.GetEdges(), com.mxgraph.mxGraph.GetEdgesBetween(), and com.mxgraph.mxGraph.GetOpposites().
Invalidate()
void com.mxgraph.mxGraphView.Invalidate () inline
Invalidates all cell states.
RemoveState() [1/2]
mxCellState com.mxgraph.mxGraphView.RemoveState (Object cell) inline
Shortcut to removeState with recurse set to false.
RemoveState() [2/2]
mxCellState com.mxgraph.mxGraphView.RemoveState (Object cell, Boolean recurse) inline
Removes and returns the mxCellState for the given cell.
Parameters
cell mxCell for which the mxCellState should be removed.
Returns
Returns the mxCellState that has been removed.
References com.mxgraph.mxIGraphModel.GetChildAt(), com.mxgraph.mxIGraphModel.GetChildCount(), and com.mxgraph.mxGraph.Model.
Revalidate()
void com.mxgraph.mxGraphView.Revalidate () inline
First invalidates, then validates all cell states.
Referenced by com.mxgraph.mxGraph.GraphModelChanged().
TransformControlPoint()
mxPoint com.mxgraph.mxGraphView.TransformControlPoint (mxCellState state, mxPoint pt) inline
Transforms the given control point to an absolute point.
References com.mxgraph.mxCellState.Origin, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateBoundingBox()
mxRectangle com.mxgraph.mxGraphView.UpdateBoundingBox (mxCellState state) inline
Updates the bounding box in the given cell state.
Parameters
state Cell state whose bounding box should be updated.
Returns
References com.mxgraph.mxRectangle.Add(), com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, com.mxgraph.mxConstants.ALIGN_TOP, com.mxgraph.mxConstants.ARROW_WIDTH, com.mxgraph.mxCellState.BoundingBox, com.mxgraph.mxCellState.Cell, com.mxgraph.mxConstants.DEFAULT_IMAGESIZE, com.mxgraph.mxConstants.DEFAULT_MARKERSIZE, com.mxgraph.mxUtils.GetBoundingBox(), com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxUtils.GetInt(), com.mxgraph.mxRectangle.GetRectangle(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxRectangle.Grow(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxIGraphModel.IsEdge(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxCellState.LabelBounds, com.mxgraph.mxGraph.Model, com.mxgraph.mxConstants.SHADOW_OFFSETX, com.mxgraph.mxConstants.SHADOW_OFFSETY, com.mxgraph.mxConstants.SHAPE_ARROW, com.mxgraph.mxConstants.SHAPE_LABEL, com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_ENDARROW, com.mxgraph.mxConstants.STYLE_IMAGE, com.mxgraph.mxConstants.STYLE_IMAGE_ALIGN, com.mxgraph.mxConstants.STYLE_IMAGE_HEIGHT, com.mxgraph.mxConstants.STYLE_IMAGE_VERTICAL_ALIGN, com.mxgraph.mxConstants.STYLE_IMAGE_WIDTH, com.mxgraph.mxConstants.STYLE_OVERFLOW, com.mxgraph.mxConstants.STYLE_ROTATION, com.mxgraph.mxConstants.STYLE_SHADOW, com.mxgraph.mxConstants.STYLE_SHAPE, com.mxgraph.mxConstants.STYLE_STARTARROW, com.mxgraph.mxConstants.STYLE_STROKEWIDTH, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateCellState()
void com.mxgraph.mxGraphView.UpdateCellState (mxCellState state, mxCellState source, mxCellState target) inline
Updates the given cell state.
Parameters
state
References com.mxgraph.mxCellState.AbsoluteOffset, com.mxgraph.mxCellState.Cell, com.mxgraph.mxGraph.GetCellGeometry(), com.mxgraph.mxGraph.GetChildOffsetForCell(), com.mxgraph.mxIGraphModel.GetParent(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxIGraphModel.IsEdge(), com.mxgraph.mxIGraphModel.IsVertex(), com.mxgraph.mxCellState.Length, com.mxgraph.mxGraph.Model, com.mxgraph.mxGeometry.Offset, com.mxgraph.mxCellState.Origin, com.mxgraph.mxGeometry.Relative, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateEdgeBounds()
void com.mxgraph.mxGraphView.UpdateEdgeBounds (mxCellState state) inline
Updates the given state using the bounding box of the absolute points. Also updates terminal distance, length and segments.
Parameters
state Cell state whose bounds should be updated.
References com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxCellState.Cell, com.mxgraph.mxRectangle.Height, com.mxgraph.mxCellState.Length, com.mxgraph.mxCellState.Segments, com.mxgraph.mxCellState.TerminalDistance, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateEdgeState()
void com.mxgraph.mxGraphView.UpdateEdgeState (mxCellState state, mxGeometry geo, mxCellState source, mxCellState target) inline
Validates the given cell state.
References com.mxgraph.mxCellState.AbsoluteOffset, com.mxgraph.mxCellState.AbsolutePointCount(), com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxCellState.Cell, com.mxgraph.mxIGraphModel.GetTerminal(), com.mxgraph.mxGeometry.GetTerminalPoint(), com.mxgraph.mxGraph.Model, and com.mxgraph.mxGeometry.Points.
UpdateFixedTerminalPoint()
void com.mxgraph.mxGraphView.UpdateFixedTerminalPoint (mxCellState edge, mxCellState terminal, bool source, mxConnectionConstraint constraint) inline
Sets the fixed source or target terminal point on the given edge.
Parameters
edge State whose terminal point should be updated.
terminal State which represents the actual terminal.
source Boolean that specifies if the terminal is the source.
constraint Constraint that specifies the connection.
References com.mxgraph.mxCellState.Cell, com.mxgraph.mxGraph.GetCellGeometry(), com.mxgraph.mxGraph.GetConnectionPoint(), com.mxgraph.mxGeometry.GetTerminalPoint(), com.mxgraph.mxCellState.Origin, com.mxgraph.mxCellState.SetAbsoluteTerminalPoint(), com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateFixedTerminalPoints()
void com.mxgraph.mxGraphView.UpdateFixedTerminalPoints (mxCellState edge, mxCellState source, mxCellState target) inline
Sets the initial absolute terminal points in the given state before the edge style is computed.
Parameters
edge Cell state whose initial terminal points should be updated.
source Cell state which represents the source terminal.
target Cell state which represents the target terminal.
References com.mxgraph.mxGraph.GetConnectionConstraint().
UpdateFloatingTerminalPoint()
void com.mxgraph.mxGraphView.UpdateFloatingTerminalPoint (mxCellState edge, mxCellState start, mxCellState end, bool source) inline
Updates the absolute terminal point in the given state for the given start and end state, where start is the source if source is true.
Parameters
edge State whose terminal point should be updated.
start for the terminal on "this" side of the edge.
end for the terminal on the other side of the edge.
source Boolean indicating if start is the source terminal state.
References com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxGraph.IsOrthogonal(), com.mxgraph.mxCellState.SetAbsoluteTerminalPoint(), com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_PERIMETER_SPACING, com.mxgraph.mxConstants.STYLE_SOURCE_PERIMETER_SPACING, and com.mxgraph.mxConstants.STYLE_TARGET_PERIMETER_SPACING.
UpdateFloatingTerminalPoints()
void com.mxgraph.mxGraphView.UpdateFloatingTerminalPoints (mxCellState state, mxCellState source, mxCellState target) inline
Updates the terminal points in the given state after the edge style was computed for the edge.
Parameters
state State whose terminal points should be updated.
source State that represents the source terminal.
target State that represents the target terminal.
References com.mxgraph.mxCellState.AbsolutePointCount(), and com.mxgraph.mxCellState.AbsolutePoints.
UpdateLabelBounds()
void com.mxgraph.mxGraphView.UpdateLabelBounds (mxCellState state) inline
Updates the label bounds in the given state.
Parameters
state
References com.mxgraph.mxCellState.AbsoluteOffset, com.mxgraph.mxCellState.Cell, com.mxgraph.mxGraph.GetLabel(), com.mxgraph.mxUtils.GetLabelPaintBounds(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxIGraphModel.IsEdge(), com.mxgraph.mxCellState.LabelBounds, com.mxgraph.mxGraph.Model, com.mxgraph.mxCellState.Style, and com.mxgraph.mxConstants.STYLE_OVERFLOW.
UpdatePoints()
void com.mxgraph.mxGraphView.UpdatePoints (mxCellState edge, List< mxPoint > points, mxCellState source, mxCellState target) inline
Updates the absolute points in the given state using the specified array of points as the relative points.
Parameters
edge Cell state whose absolute points should be updated.
points Array of points that constitute the relative points.
source Cell that represents the source terminal.
target Cell that represents the target terminal.
References com.mxgraph.mxCellState.AbsolutePoints, and com.mxgraph.mxEdgeStyleFunction().
UpdateVertexLabelOffset()
void com.mxgraph.mxGraphView.UpdateVertexLabelOffset (mxCellState state) inline
Updates the absoluteOffset of the given vertex cell state. This takes into account the label position styles.
Parameters
state Cell state whose absolute offset should be updated.
References com.mxgraph.mxCellState.AbsoluteOffset, com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, com.mxgraph.mxConstants.ALIGN_TOP, com.mxgraph.mxUtils.GetString(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_LABEL_POSITION, com.mxgraph.mxConstants.STYLE_VERTICAL_LABEL_POSITION, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
UpdateVertexState()
void com.mxgraph.mxGraphView.UpdateVertexState (mxCellState state, mxGeometry geo) inline
Validates the given cell state.
Validate()
void com.mxgraph.mxGraphView.Validate () inline
First validates all bounds and then validates all points recursively on all visible cells.
References com.mxgraph.mxGraph.Model, and com.mxgraph.mxIGraphModel.Root.
ValidateCell() [1/2]
Object com.mxgraph.mxGraphView.ValidateCell (Object cell) inline
Shortcut to validateCell with visible set to true.
Referenced by com.mxgraph.mxCellRenderer.DrawCells().
ValidateCell() [2/2]
Object com.mxgraph.mxGraphView.ValidateCell (Object cell, Boolean visible) inline
Recursively creates the cell state for the given cell if visible is true and the given cell is visible. If the cell is not visible but the state exists then it is removed using removeState.
Parameters
cell Cell whose cell state should be created.
visible Boolean indicating if the cell should be visible.
References com.mxgraph.mxIGraphModel.GetChildAt(), com.mxgraph.mxIGraphModel.GetChildCount(), com.mxgraph.mxGraph.IsCellCollapsed(), com.mxgraph.mxGraph.IsCellVisible(), and com.mxgraph.mxGraph.Model.
ValidateCellState() [1/2]
mxCellState com.mxgraph.mxGraphView.ValidateCellState (Object cell) inline
Shortcut to validateCellState with recurse set to true.
Referenced by com.mxgraph.mxCellRenderer.DrawCells().
ValidateCellState() [2/2]
mxCellState com.mxgraph.mxGraphView.ValidateCellState (Object cell, Boolean recurse) inline
Validates the cell state for the given cell.
Parameters
cell Cell whose cell state should be validated.
recurse Boolean indicating if the children of the cell should be validated.
Returns
References com.mxgraph.mxIGraphModel.GetChildAt(), com.mxgraph.mxIGraphModel.GetChildCount(), com.mxgraph.mxIGraphModel.GetParent(), com.mxgraph.mxCellState.Invalid, com.mxgraph.mxIGraphModel.IsEdge(), com.mxgraph.mxIGraphModel.IsVertex(), and com.mxgraph.mxGraph.Model.
Member Data Documentation
eventsEnabled
bool com.mxgraph.mxGraphView.eventsEnabled = true protected
Specifies if the view should be revalidated if the scale or translation changes.
graph
mxGraph com.mxgraph.mxGraphView.graph protected
Reference to the enclosing graph.
graphBounds
mxRectangle com.mxgraph.mxGraphView.graphBounds = new mxRectangle() protected
Caches the current bounds of the graph.
scale
double com.mxgraph.mxGraphView.scale = 1 protected
Specifies the scale. Default is 1 (100%).
states
Dictionary<Object, mxCellState> com.mxgraph.mxGraphView.states = new Dictionary<Object, mxCellState>() protected
Maps from cells to cell states.
translate
mxPoint com.mxgraph.mxGraphView.translate = new mxPoint(0, 0) protected
Point that specifies the current translation. Default is a new empty point.
Property Documentation
Graph
mxGraph com.mxgraph.mxGraphView.Graph get
Returns the enclosing graph.
GraphBounds
mxRectangle com.mxgraph.mxGraphView.GraphBounds get set
Returns the cached diagram bounds.
Referenced by com.mxgraph.mxGraph.GetGraphBounds().
IsEventsEnabled
bool com.mxgraph.mxGraphView.IsEventsEnabled get set
Sets or returns the current scale.
Referenced by com.mxgraph.mxCellRenderer.DrawCells().
Scale
double com.mxgraph.mxGraphView.Scale get set
Sets or returns the current scale.
Referenced by com.mxgraph.mxCellRenderer.DrawCells(), com.mxgraph.mxStencil.DrawShape(), com.mxgraph.mxGraph.HitsSwimlaneContent(), and com.mxgraph.mxStencil.PaintShape().
States
Dictionary<Object, mxCellState> com.mxgraph.mxGraphView.States get set
Sets or returns the current translation.
Referenced by com.mxgraph.mxCellRenderer.DrawCells().
Translate
mxPoint com.mxgraph.mxGraphView.Translate get set
Sets or returns the current translation.
The documentation for this class was generated from the following file:
src/view/mxGraphView.cs