mxGraph: com.mxgraph.mxGeometry Class Reference
com.mxgraph.mxGeometry Class Reference
Represents the geometry of a cell. For vertices, the geometry consists of the x- and y-location, as well as the width and height. For edges, the edge either defines the source- and target-terminal, or the geometry defines the respective terminal points.
Public Member Functions
mxGeometry ()
Constructs a new geometry at (0, 0) with the width and height set to 0.
mxGeometry (double x, double y, double width, double height)
Constructs a geometry using the given parameters.
mxGeometry (mxGeometry geometry)
Constructs a copy of the given geometry.
mxPoint GetTerminalPoint (bool source)
Returns the point representing the source or target point of this edge. This is only used if the edge has no source or target vertex.
mxPoint SetTerminalPoint (mxPoint point, bool source)
Sets the sourcePoint or targetPoint to the given point and returns the new point.
void Translate (double dx, double dy)
Translates the geometry by the specified amount. That is, x and y of the geometry, the sourcePoint, targetPoint and all elements of points are translated by the given amount. X and y are only translated if the geometry is not relative. If TRANSLATE_CONTROL_POINTS is false, then are not modified by this function.
new mxGeometry Clone ()
Returns a new instance of the same geometry.
Public Member Functions inherited from com.mxgraph.mxRectangle
mxRectangle ()
Constructs a new rectangle at (0, 0) with the width and height set to 0.
mxRectangle (mxRectangle rect)
Constructs a copy of the given rectangle.
mxRectangle (Rectangle rect)
Constructs a copy of the given rectangle.
mxRectangle (double x, double y, double width, double height)
Constructs a rectangle using the given parameters.
void setRect (double x, double y, double w, double h)
Sets this rectangle to the specified values
double GetCenterX ()
Returns the x-coordinate of the center.
double GetCenterY ()
Returns the y-coordinate of the center.
void Add (mxRectangle rect)
Adds the given rectangle to this rectangle.
void Grow (double amount)
Grows the rectangle by the given amount, that is, this method subtracts the given amount from the x- and y-coordinates and adds twice the amount to the width and height.
bool Contains (double x, double y)
Returns true if this rectangle contains the given point (x, y).
Rectangle GetRectangle ()
Returns the bounds as a new rectangle.
new Boolean Equals (Object obj)
Returns true if the given object equals this rectangle.
new mxRectangle Clone ()
Returns a new instance of the same rectangle.
Public Member Functions inherited from com.mxgraph.mxPoint
mxPoint ()
Constructs a new point at (0, 0).
mxPoint (Point point)
Constructs a new point at the location of the given point.
mxPoint (mxPoint point)
Constructs a new point at the location of the given point.
mxPoint (double x, double y)
Constructs a new point at (x, y).
Point GetPoint ()
Returns the coordinates as a new point.
new Boolean Equals (Object obj)
Returns true if the given object equals this point.
mxPoint Clone ()
Returns a new instance of the same point.
Static Public Attributes
static bool TRANSLATE_CONTROL_POINTS = true
Global switch to translate the points in translate. Default is true.
Protected Attributes
mxRectangle alternateBounds
Stores alternate values for x, y, width and height in a rectangle. Default is null.
mxPoint sourcePoint
Defines the source-point of the edge. This is used if the corresponding edge does not have a source vertex. Otherwise it is ignored. Default is null.
mxPoint targetPoint
Defines the target-point of the edge. This is used if the corresponding edge does not have a source vertex. Otherwise it is ignored. Default is null.
mxPoint offset
Holds the offset of the label for edges. This is the absolute vector between the center of the edge and the top, left point of the label. Default is null.
List< mxPoint > points
List of mxPoints which specifies the control points along the edge. These points are the intermediate points on the edge, for the endpoints use targetPoint and sourcePoint or set the terminals of the edge to a non-null value. Default is null.
bool relative = false
Specifies if the coordinates in the geometry are to be interpreted as relative coordinates. Default is false. This is used to mark a geometry with an x- and y-coordinate that is used to describe an edge label position.
Protected Attributes inherited from com.mxgraph.mxRectangle
double width
Holds the width. Default is 0.
double height
Holds the height. Default is 0.
Protected Attributes inherited from com.mxgraph.mxPoint
double x
Holds the x-coordinate of the point. Default is 0.
double y
Holds the y-coordinate of the point. Default is 0.
Properties
mxRectangle AlternateBounds [get, set]
Sets or returns the alternate bounds.
mxPoint SourcePoint [get, set]
Sets or returns the source point.
mxPoint TargetPoint [get, set]
Sets or returns the target point.
List< mxPoint > Points [get, set]
Sets or returns the list of control points.
mxPoint Offset [get, set]
Sets or returns the offset.
bool Relative [get, set]
Sets or returns if the geometry is relative.
Properties inherited from com.mxgraph.mxRectangle
double Width [get, set]
Sets or returns the width of the rectangle.
double Height [get, set]
Sets or returns the height of the rectangle.
Properties inherited from com.mxgraph.mxPoint
double X [get, set]
Sets or returns the x-coordinate of the point.
double Y [get, set]
Sets or returns the y-coordinate of the point.
Detailed Description
Represents the geometry of a cell. For vertices, the geometry consists of the x- and y-location, as well as the width and height. For edges, the edge either defines the source- and target-terminal, or the geometry defines the respective terminal points.
Constructor & Destructor Documentation
mxGeometry() [1/3]
com.mxgraph.mxGeometry.mxGeometry () inline
Constructs a new geometry at (0, 0) with the width and height set to 0.
mxGeometry() [2/3]
com.mxgraph.mxGeometry.mxGeometry (double x, double y, double width, double height) inline
Constructs a geometry using the given parameters.
Parameters
x X-coordinate of the new geometry.
y Y-coordinate of the new geometry.
width Width of the new geometry.
height Height of the new geometry.
mxGeometry() [3/3]
com.mxgraph.mxGeometry.mxGeometry (mxGeometry geometry) inline
Constructs a copy of the given geometry.
Parameters
geometry Geometry to construct a copy of.
References com.mxgraph.mxGeometry.alternateBounds, com.mxgraph.mxPoint.Clone(), com.mxgraph.mxRectangle.Clone(), com.mxgraph.mxGeometry.offset, com.mxgraph.mxGeometry.points, com.mxgraph.mxGeometry.relative, com.mxgraph.mxGeometry.sourcePoint, and com.mxgraph.mxGeometry.targetPoint.
Member Function Documentation
Clone()
new mxGeometry com.mxgraph.mxGeometry.Clone () inline
Returns a new instance of the same geometry.
Returns
Returns a clone of the geometry.
Referenced by com.mxgraph.mxCell.Clone(), com.mxgraph.mxFastOrganicLayout.execute(), and com.mxgraph.mxGraphModel.UpdateEdgeParent().
GetTerminalPoint()
mxPoint com.mxgraph.mxGeometry.GetTerminalPoint (bool source) inline
Returns the point representing the source or target point of this edge. This is only used if the edge has no source or target vertex.
Parameters
source Boolean that specifies if the source or target point should be returned.
Returns
Returns the source or target point.
Referenced by com.mxgraph.mxGraphView.UpdateEdgeState(), and com.mxgraph.mxGraphView.UpdateFixedTerminalPoint().
SetTerminalPoint()
mxPoint com.mxgraph.mxGeometry.SetTerminalPoint (mxPoint point, bool source) inline
Sets the sourcePoint or targetPoint to the given point and returns the new point.
Parameters
point Point to be used as the new source or target point.
source Boolean that specifies if the source or target point should be set.
Returns
Returns the new point.
Translate()
void com.mxgraph.mxGeometry.Translate (double dx, double dy) inline
Translates the geometry by the specified amount. That is, x and y of the geometry, the sourcePoint, targetPoint and all elements of points are translated by the given amount. X and y are only translated if the geometry is not relative. If TRANSLATE_CONTROL_POINTS is false, then are not modified by this function.
Parameters
dx Integer that specifies the x-coordinate of the translation.
dy Integer that specifies the y-coordinate of the translation.
References com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxGraphModel.UpdateEdgeParent().
Member Data Documentation
alternateBounds
mxRectangle com.mxgraph.mxGeometry.alternateBounds protected
Stores alternate values for x, y, width and height in a rectangle. Default is null.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
offset
mxPoint com.mxgraph.mxGeometry.offset protected
Holds the offset of the label for edges. This is the absolute vector between the center of the edge and the top, left point of the label. Default is null.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
points
List<mxPoint> com.mxgraph.mxGeometry.points protected
List of mxPoints which specifies the control points along the edge. These points are the intermediate points on the edge, for the endpoints use targetPoint and sourcePoint or set the terminals of the edge to a non-null value. Default is null.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
relative
bool com.mxgraph.mxGeometry.relative = false protected
Specifies if the coordinates in the geometry are to be interpreted as relative coordinates. Default is false. This is used to mark a geometry with an x- and y-coordinate that is used to describe an edge label position.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
sourcePoint
mxPoint com.mxgraph.mxGeometry.sourcePoint protected
Defines the source-point of the edge. This is used if the corresponding edge does not have a source vertex. Otherwise it is ignored. Default is null.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
targetPoint
mxPoint com.mxgraph.mxGeometry.targetPoint protected
Defines the target-point of the edge. This is used if the corresponding edge does not have a source vertex. Otherwise it is ignored. Default is null.
Referenced by com.mxgraph.mxGeometry.mxGeometry().
TRANSLATE_CONTROL_POINTS
bool com.mxgraph.mxGeometry.TRANSLATE_CONTROL_POINTS = true static
Global switch to translate the points in translate. Default is true.
Property Documentation
AlternateBounds
mxRectangle com.mxgraph.mxGeometry.AlternateBounds get set
Sets or returns the alternate bounds.
Offset
mxPoint com.mxgraph.mxGeometry.Offset get set
Sets or returns the offset.
Referenced by com.mxgraph.mxGraphView.GetPoint(), and com.mxgraph.mxGraphView.UpdateCellState().
Points
List<mxPoint> com.mxgraph.mxGeometry.Points get set
Sets or returns the list of control points.
Referenced by com.mxgraph.mxGraphView.UpdateEdgeState().
Relative
bool com.mxgraph.mxGeometry.Relative get set
Sets or returns if the geometry is relative.
Referenced by com.mxgraph.mxGraph.CreateEdge(), com.mxgraph.mxGraph.CreateVertex(), com.mxgraph.mxGraphView.GetPoint(), and com.mxgraph.mxGraphView.UpdateCellState().
SourcePoint
mxPoint com.mxgraph.mxGeometry.SourcePoint get set
Sets or returns the source point.
TargetPoint
mxPoint com.mxgraph.mxGeometry.TargetPoint get set
Sets or returns the target point.
The documentation for this class was generated from the following file:
src/model/mxGeometry.cs