mxGraph: com.mxgraph.mxCellRenderer Class Reference
com.mxgraph.mxCellRenderer Class Reference
Class that can draw an independent array of cells.
Classes
class CanvasFactory
Defines the requirements for a class that can create canvases.
class ImageCanvasFactory
FIXME: Use anonymous class in CreateImage with invocation parameters in factory method code.
Static Public Member Functions
static mxICanvas DrawCells (mxGraph graph, Object[] cells, double scale, mxRectangle clip, CanvasFactory factory)
Draws the given cells using a Graphics2D canvas and returns the buffered image that represents the cells.
static Image CreateImage (mxGraph graph, Object[] cells, double scale, Color? background, bool antiAlias, mxRectangle clip)
Creates an image for the given arguments.
static Image CreateImage (mxGraph graph, Object[] cells, double scale, Color? background, bool antiAlias, mxRectangle clip, mxGdiCanvas graphicsCanvas)
Creates an image for the given arguments.
Detailed Description
Class that can draw an independent array of cells.
Member Function Documentation
CreateImage() [1/2]
static Image com.mxgraph.mxCellRenderer.CreateImage (mxGraph graph, Object [] cells, double scale, Color? background, bool antiAlias, mxRectangle clip) inline static
Creates an image for the given arguments.
CreateImage() [2/2]
static Image com.mxgraph.mxCellRenderer.CreateImage (mxGraph graph, Object [] cells, double scale, Color? background, bool antiAlias, mxRectangle clip, mxGdiCanvas graphicsCanvas) inline static
Creates an image for the given arguments.
References com.mxgraph.mxImageCanvas.Destroy().
DrawCells()
static mxICanvas com.mxgraph.mxCellRenderer.DrawCells (mxGraph graph, Object [] cells, double scale, mxRectangle clip, CanvasFactory factory) inline static
Draws the given cells using a Graphics2D canvas and returns the buffered image that represents the cells.
References com.mxgraph.mxCellRenderer.CanvasFactory.CreateCanvas(), com.mxgraph.mxGraph.DrawCell(), com.mxgraph.mxGraph.GetPaintBounds(), com.mxgraph.mxRectangle.GetRectangle(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxGraphView.IsEventsEnabled, com.mxgraph.mxGraph.Model, com.mxgraph.mxIGraphModel.Root, com.mxgraph.mxICanvas.Scale, com.mxgraph.mxGraphView.Scale, com.mxgraph.mxGraphView.States, com.mxgraph.mxICanvas.Translate, com.mxgraph.mxGraphView.ValidateCell(), com.mxgraph.mxGraphView.ValidateCellState(), com.mxgraph.mxGraph.View, and com.mxgraph.mxRectangle.Width.
The documentation for this class was generated from the following file:
src/utils/mxCellRenderer.cs