mxGraph: com.mxgraph.mxImageCanvas Class Reference
com.mxgraph.mxImageCanvas Class Reference
Implements a canvas that draws onto an image.
Public Member Functions
mxImageCanvas (mxGdiCanvas canvas, int width, int height, Color? background, bool antiAlias)
Object DrawCell (mxCellState state)
see com.mxgraph.mxICanvas.DrawCell()
Object DrawLabel (string text, mxCellState state, bool html)
see com.mxgraph.mxICanvas.DrawLabel()
Image Destroy ()
Destroys this canvas and all allocated resources.
Protected Attributes
mxGdiCanvas canvas
Inner canvas used for the actual rendering.
Graphics previousGraphics
Stores the previous graphics reference of the inner canvas.
Image image
Stores the image that holds the graphics.
Properties
mxGdiCanvas GdiCanvas [get]
Returns the inner canvas.
Image Image [get]
Returns the image that hold the graphics.
Point Translate [get, set]
see com.mxgraph.mxICanvas.Translate
double Scale [get, set]
see com.mxgraph.mxICanvas.Translate
Properties inherited from com.mxgraph.mxICanvas
Point Translate [get, set]
Sets or returns the user object of the cell.
double Scale [get, set]
Sets or returns the user object of the cell.
Detailed Description
Implements a canvas that draws onto an image.
Constructor & Destructor Documentation
mxImageCanvas()
com.mxgraph.mxImageCanvas.mxImageCanvas (mxGdiCanvas canvas, int width, int height, Color? background, bool antiAlias) inline
Parameters
canvas
width
height
background
antiAlias
References com.mxgraph.mxUtils.CreateImage(), and com.mxgraph.mxGdiCanvas.Graphics.
Member Function Documentation
Destroy()
Image com.mxgraph.mxImageCanvas.Destroy () inline
Destroys this canvas and all allocated resources.
References com.mxgraph.mxGdiCanvas.Graphics.
Referenced by com.mxgraph.mxCellRenderer.CreateImage().
DrawCell()
Object com.mxgraph.mxImageCanvas.DrawCell (mxCellState state) inline
see com.mxgraph.mxICanvas.DrawCell()
Implements com.mxgraph.mxICanvas.
References com.mxgraph.mxGdiCanvas.DrawCell().
DrawLabel()
Object com.mxgraph.mxImageCanvas.DrawLabel (string text, mxCellState state, bool html) inline
see com.mxgraph.mxICanvas.DrawLabel()
Implements com.mxgraph.mxICanvas.
References com.mxgraph.mxGdiCanvas.DrawLabel().
Member Data Documentation
canvas
mxGdiCanvas com.mxgraph.mxImageCanvas.canvas protected
Inner canvas used for the actual rendering.
image
Image com.mxgraph.mxImageCanvas.image protected
Stores the image that holds the graphics.
previousGraphics
Graphics com.mxgraph.mxImageCanvas.previousGraphics protected
Stores the previous graphics reference of the inner canvas.
Property Documentation
GdiCanvas
mxGdiCanvas com.mxgraph.mxImageCanvas.GdiCanvas get
Returns the inner canvas.
Image
Image com.mxgraph.mxImageCanvas.Image get
Returns the image that hold the graphics.
Scale
double com.mxgraph.mxImageCanvas.Scale get set
see com.mxgraph.mxICanvas.Translate
Translate
Point com.mxgraph.mxImageCanvas.Translate get set
see com.mxgraph.mxICanvas.Translate
Referenced by com.mxgraph.mxGraphViewImageReader.CreateCanvas().
The documentation for this class was generated from the following file:
src/canvas/mxImageCanvas.cs