mxGraph: com.mxgraph.mxGdiCanvas2D Class Reference
com.mxgraph.mxGdiCanvas2D Class Reference
Used for exporting images. To render to an image from a given XML string, graph size and and background color, the following code is used:
Classes
class CanvasState
Public Member Functions
mxGdiCanvas2D (Graphics g)
void Save ()
void Restore ()
void Scale (double value)
Sets the given scale.
void Translate (double dx, double dy)
Translates the canvas.
void Rotate (double theta, bool flipH, bool flipV, double cx, double cy)
Rotates the canvas.
void SetShadowOffset (double dx, double dy)
Prepares the canvas to draw a gradient.
void SetGradient (String color1, String color2, double x, double y, double w, double h, String direction, double alpha1, double alpha2)
Sets the given gradient.
void Rect (double x, double y, double w, double h)
Draws a rectangle.
void Roundrect (double x, double y, double w, double h, double dx, double dy)
void Ellipse (double x, double y, double w, double h)
Draws an ellipse.
void Image (double x, double y, double w, double h, String src, bool aspect, bool flipH, bool flipV)
Draws an image.
void Text (double x, double y, double w, double h, string str, string align, string valign, bool wrap, string format, string overflow, bool clip, double rotation, string dir)
void Begin ()
void MoveTo (double x, double y)
void LineTo (double x, double y)
void QuadTo (double x1, double y1, double x2, double y2)
void CurveTo (double x1, double y1, double x2, double y2, double x3, double y3)
void Close ()
void Stroke ()
void Fill ()
void FillAndStroke ()
Public Member Functions inherited from com.mxgraph.mxICanvas2D
void SetGradient (string color1, string color2, double x, double y, double w, double h, string direction, double alpha1, double alpha2)
Prepares the canvas to draw a gradient.
void Image (double x, double y, double w, double h, string src, bool aspect, bool flipH, bool flipV)
Draws the given image.
Static Public Member Functions
static StringFormat CreateStringFormat (string align, string valign, bool wrap, bool clip)
Creates the specified string format.
Protected Member Functions
Color ParseColor (string hex)
Helper method that uses mxUtils#parseColor(String). Subclassers
Color ParseColor (string hex, double alpha)
Helper method that uses mxUtils#parseColor(String). Subclassers
void DrawImage (Image image, Rectangle bounds)
Implements the call to the graphics API.
Image LoadImage (String src)
Loads the specified image.
Rectangle GetImageBounds (Image img, double x, double y, double w, double h, bool aspect)
Returns the bounds for the given image.
Size GetImageSize (Image image)
Returns the size for the given image.
void ConfigureImageGraphics (double x, double y, double w, double h, bool flipH, bool flipV)
PointF GetMargin (String align, String valign)
void PaintCurrentPath (bool filled, bool stroked)
void PaintShadow (bool filled, bool stroked)
void UpdateFont ()
Font CreateFont (String family, FontStyle style, float size)
String GetFontName (String family)
Returns a font name for the given font family.
void UpdatePen ()
Protected Attributes
bool matchHtmlAlignment = true
matchHtmlAlignment
bool htmlAsPlainText = true
htmlAsPlainText
bool wrapPlainText = true
htmlAsPlainText
Graphics graphics
CanvasState state = new CanvasState()
Stack< CanvasState > stack = new Stack<CanvasState>()
GraphicsPath currentPath
mxPoint lastPoint
Holds the last point of a moveTo or lineTo operation to determine if the
Font lastFont = null
FontCaching
FontStyle lastFontStyle = 0
FontCaching
float lastFontSize = 0
FontCaching
String lastFontFamily = ""
FontCaching
Properties
double StrokeWidth [set]
Sets the strokewidth.
string StrokeColor [set]
bool Dashed [set]
Specifies if lines are dashed.
bool FixDash [set]
Specifies if lines are dashed.
string DashPattern [set]
Sets the dashpattern.
string LineCap [set]
Sets the linecap.
string LineJoin [set]
Sets the linejoin.
double MiterLimit [set]
Sets the miterlimit.
double FontSize [set]
Sets the fontsize.
string FontColor [set]
Sets the fontcolor.
string FontBackgroundColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontBorderColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontFamily [set]
Sets the font family.
int FontStyle [set]
Sets the given fontstyle.
double Alpha [set]
Sets the given alpha.
double StrokeAlpha [set]
Sets the given alpha.
double FillAlpha [set]
Sets the given alpha.
string FillColor [set]
Sets the given fillcolor.
bool Shadow [set]
Default value mxConstants#NONE.
string ShadowColor [set]
Default value mxConstants#NONE.
double ShadowAlpha [set]
Default value 1. This method may add rendering overhead and should be used with care.
Properties inherited from com.mxgraph.mxICanvas2D
double StrokeWidth [set]
Sets the stroke width. This should default to 1 if unset.
string StrokeColor [set]
Sets the stroke color. This should default to mxConstants.NONE if unset.
bool Dashed [set]
Sets the dashed state. This should default to false if unset.
bool FixDash [set]
Sets the dashed state. This should default to false if unset.
string DashPattern [set]
Sets the dash pattern. This should default to "3 3" if unset.
string LineCap [set]
Sets the linecap. This should default to "flat" if unset.
string LineJoin [set]
Sets the linejoin. This should default to "miter" if unset.
double MiterLimit [set]
Sets the miterlimit. This should default to 10 if unset.
double FontSize [set]
Default value mxConstants.DEFAULT_FONTSIZE.
string FontColor [set]
Default value "#000000".
string FontFamily [set]
Default value mxConstants#DEFAULT_FONTFAMILY.
int FontStyle [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontBackgroundColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontBorderColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
double Alpha [set]
Default value 1. This method may add rendering overhead and should be used with care.
double FillAlpha [set]
Default value 1.
double StrokeAlpha [set]
Default value 1.
string FillColor [set]
Default value mxConstants#NONE.
bool Shadow [set]
Default value mxConstants#NONE.
string ShadowColor [set]
Default value mxConstants#NONE.
double ShadowAlpha [set]
Default value 1. This method may add rendering overhead and should be used with care.
Detailed Description
Used for exporting images.
To render to an image from a given XML string, graph size and and background color, the following code is used:
Image image = mxUtils.CreateImage(width, height, background); Graphics g = Graphics.FromImage(image); g.SmoothingMode = SmoothingMode.HighQuality; mxSaxOutputHandler handler = new mxSaxOutputHandler(new mxGdiCanvas2D(g)); handler.Read(new XmlTextReader(new StringReader(xml)));
Text rendering is available for plain text only, with optional word wrapping.
Constructor & Destructor Documentation
mxGdiCanvas2D()
com.mxgraph.mxGdiCanvas2D.mxGdiCanvas2D (Graphics g) inline
Constructs a new graphics export canvas.
Member Function Documentation
Begin()
void com.mxgraph.mxGdiCanvas2D.Begin () inline
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Close()
void com.mxgraph.mxGdiCanvas2D.Close () inline
Closes the current path.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
ConfigureImageGraphics()
void com.mxgraph.mxGdiCanvas2D.ConfigureImageGraphics (double x, double y, double w, double h, bool flipH, bool flipV) inline protected
Creates a graphic instance for rendering an image.
CreateFont()
Font com.mxgraph.mxGdiCanvas2D.CreateFont (String family, FontStyle style, float size) inline protected
Hook for subclassers to implement font caching.
CreateStringFormat()
static StringFormat com.mxgraph.mxGdiCanvas2D.CreateStringFormat (string align, string valign, bool wrap, bool clip) inline static
Creates the specified string format.
References com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, and com.mxgraph.mxConstants.ALIGN_TOP.
CurveTo()
void com.mxgraph.mxGdiCanvas2D.CurveTo (double x1, double y1, double x2, double y2, double x3, double y3) inline
Implements com.mxgraph.mxICanvas2D.
References com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxStencil.DrawElement().
DrawImage()
void com.mxgraph.mxGdiCanvas2D.DrawImage (Image image, Rectangle bounds) inline protected
Implements the call to the graphics API.
Ellipse()
void com.mxgraph.mxGdiCanvas2D.Ellipse (double x, double y, double w, double h) inline
Draws an ellipse.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Fill()
void com.mxgraph.mxGdiCanvas2D.Fill () inline
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
FillAndStroke()
void com.mxgraph.mxGdiCanvas2D.FillAndStroke () inline
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
GetFontName()
String com.mxgraph.mxGdiCanvas2D.GetFontName (String family) inline protected
Returns a font name for the given font family.
GetImageBounds()
Rectangle com.mxgraph.mxGdiCanvas2D.GetImageBounds (Image img, double x, double y, double w, double h, bool aspect) inline protected
Returns the bounds for the given image.
GetImageSize()
Size com.mxgraph.mxGdiCanvas2D.GetImageSize (Image image) inline protected
Returns the size for the given image.
Image()
void com.mxgraph.mxGdiCanvas2D.Image (double x, double y, double w, double h, String src, bool aspect, bool flipH, bool flipV) inline
Draws an image.
Referenced by com.mxgraph.mxStencil.DrawElement().
LineTo()
void com.mxgraph.mxGdiCanvas2D.LineTo (double x, double y) inline
Implements com.mxgraph.mxICanvas2D.
References com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxStencil.DrawElement().
LoadImage()
Image com.mxgraph.mxGdiCanvas2D.LoadImage (String src) inline protected
Loads the specified image.
References com.mxgraph.mxUtils.LoadImage().
MoveTo()
void com.mxgraph.mxGdiCanvas2D.MoveTo (double x, double y) inline
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
PaintCurrentPath()
void com.mxgraph.mxGdiCanvas2D.PaintCurrentPath (bool filled, bool stroked) inline protected
Parameters
value
PaintShadow()
void com.mxgraph.mxGdiCanvas2D.PaintShadow (bool filled, bool stroked) inline protected
Parameters
value
ParseColor() [1/2]
Color com.mxgraph.mxGdiCanvas2D.ParseColor (string hex) inline protected
Helper method that uses mxUtils#parseColor(String). Subclassers
can override this to implement caching for frequently used colors.
ParseColor() [2/2]
Color com.mxgraph.mxGdiCanvas2D.ParseColor (string hex, double alpha) inline protected
Helper method that uses mxUtils#parseColor(String). Subclassers
can override this to implement caching for frequently used colors.
References com.mxgraph.mxConstants.NONE.
QuadTo()
void com.mxgraph.mxGdiCanvas2D.QuadTo (double x1, double y1, double x2, double y2) inline
Implements com.mxgraph.mxICanvas2D.
References com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxStencil.DrawElement().
Rect()
void com.mxgraph.mxGdiCanvas2D.Rect (double x, double y, double w, double h) inline
Draws a rectangle.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Restore()
void com.mxgraph.mxGdiCanvas2D.Restore () inline
Restores the last canvas state.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Rotate()
void com.mxgraph.mxGdiCanvas2D.Rotate (double theta, bool flipH, bool flipV, double cx, double cy) inline
Rotates the canvas.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.PaintShape().
Roundrect()
void com.mxgraph.mxGdiCanvas2D.Roundrect (double x, double y, double w, double h, double dx, double dy) inline
Draws a rounded rectangle.
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Save()
void com.mxgraph.mxGdiCanvas2D.Save () inline
Saves the current canvas state.
Implements com.mxgraph.mxICanvas2D.
References com.mxgraph.mxGdiCanvas2D.CanvasState.Clone().
Referenced by com.mxgraph.mxStencil.DrawElement(), and com.mxgraph.mxStencil.PaintShape().
Scale()
void com.mxgraph.mxGdiCanvas2D.Scale (double value) inline
Sets the given scale.
Parameters
value
Implements com.mxgraph.mxICanvas2D.
SetGradient()
void com.mxgraph.mxGdiCanvas2D.SetGradient (String color1, String color2, double x, double y, double w, double h, String direction, double alpha1, double alpha2) inline
Sets the given gradient.
References com.mxgraph.mxConstants.DIRECTION_EAST, com.mxgraph.mxConstants.DIRECTION_NORTH, com.mxgraph.mxConstants.DIRECTION_SOUTH, and com.mxgraph.mxConstants.DIRECTION_WEST.
Referenced by com.mxgraph.mxStencil.PaintShape().
SetShadowOffset()
void com.mxgraph.mxGdiCanvas2D.SetShadowOffset (double dx, double dy) inline
Prepares the canvas to draw a gradient.
Implements com.mxgraph.mxICanvas2D.
Stroke()
void com.mxgraph.mxGdiCanvas2D.Stroke () inline
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawElement().
Text()
void com.mxgraph.mxGdiCanvas2D.Text (double x, double y, double w, double h, string str, string align, string valign, bool wrap, string format, string overflow, bool clip, double rotation, string dir) inline
Draws the given text.
Implements com.mxgraph.mxICanvas2D.
References com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_MIDDLE, and com.mxgraph.mxConstants.ALIGN_RIGHT.
Referenced by com.mxgraph.mxStencil.DrawElement().
Translate()
void com.mxgraph.mxGdiCanvas2D.Translate (double dx, double dy) inline
Translates the canvas.
Parameters
dx
dy
Implements com.mxgraph.mxICanvas2D.
Referenced by com.mxgraph.mxStencil.DrawShadow().
UpdateFont()
void com.mxgraph.mxGdiCanvas2D.UpdateFont () inline protected
References com.mxgraph.mxConstants.FONT_BOLD, com.mxgraph.mxConstants.FONT_ITALIC, com.mxgraph.mxConstants.FONT_SIZEFACTOR, and com.mxgraph.mxConstants.FONT_UNDERLINE.
UpdatePen()
void com.mxgraph.mxGdiCanvas2D.UpdatePen () inline protected
Member Data Documentation
currentPath
GraphicsPath com.mxgraph.mxGdiCanvas2D.currentPath protected
Holds the current path.
graphics
Graphics com.mxgraph.mxGdiCanvas2D.graphics protected
Reference to the graphics instance for painting.
htmlAsPlainText
bool com.mxgraph.mxGdiCanvas2D.htmlAsPlainText = true protected
htmlAsPlainText
lastFont
Font com.mxgraph.mxGdiCanvas2D.lastFont = null protected
FontCaching
lastFontFamily
String com.mxgraph.mxGdiCanvas2D.lastFontFamily = "" protected
FontCaching
lastFontSize
float com.mxgraph.mxGdiCanvas2D.lastFontSize = 0 protected
FontCaching
lastFontStyle
FontStyle com.mxgraph.mxGdiCanvas2D.lastFontStyle = 0 protected
FontCaching
lastPoint
mxPoint com.mxgraph.mxGdiCanvas2D.lastPoint protected
Holds the last point of a moveTo or lineTo operation to determine if the
current path is orthogonal.
matchHtmlAlignment
bool com.mxgraph.mxGdiCanvas2D.matchHtmlAlignment = true protected
matchHtmlAlignment
stack
Stack<CanvasState> com.mxgraph.mxGdiCanvas2D.stack = new Stack<CanvasState>() protected
Stack of states for save/restore.
state
CanvasState com.mxgraph.mxGdiCanvas2D.state = new CanvasState() protected
Represents the current state of the canvas.
wrapPlainText
bool com.mxgraph.mxGdiCanvas2D.wrapPlainText = true protected
htmlAsPlainText
Property Documentation
Alpha
double com.mxgraph.mxGdiCanvas2D.Alpha set
Sets the given alpha.
Referenced by com.mxgraph.mxStencil.DrawShadow(), and com.mxgraph.mxStencil.PaintShape().
Dashed
bool com.mxgraph.mxGdiCanvas2D.Dashed set
Specifies if lines are dashed.
Referenced by com.mxgraph.mxStencil.DrawElement(), and com.mxgraph.mxStencil.PaintShape().
DashPattern
string com.mxgraph.mxGdiCanvas2D.DashPattern set
Sets the dashpattern.
Referenced by com.mxgraph.mxStencil.DrawElement().
FillAlpha
double com.mxgraph.mxGdiCanvas2D.FillAlpha set
Sets the given alpha.
FillColor
string com.mxgraph.mxGdiCanvas2D.FillColor set
Sets the given fillcolor.
Referenced by com.mxgraph.mxStencil.DrawElement(), and com.mxgraph.mxStencil.PaintShape().
FixDash
bool com.mxgraph.mxGdiCanvas2D.FixDash set
Specifies if lines are dashed.
FontBackgroundColor
string com.mxgraph.mxGdiCanvas2D.FontBackgroundColor set
Default value 0. See mxConstants#STYLE_FONTSTYLE.
FontBorderColor
string com.mxgraph.mxGdiCanvas2D.FontBorderColor set
Default value 0. See mxConstants#STYLE_FONTSTYLE.
FontColor
string com.mxgraph.mxGdiCanvas2D.FontColor set
Sets the fontcolor.
Referenced by com.mxgraph.mxStencil.DrawElement().
FontFamily
string com.mxgraph.mxGdiCanvas2D.FontFamily set
Sets the font family.
Referenced by com.mxgraph.mxStencil.DrawElement().
FontSize
double com.mxgraph.mxGdiCanvas2D.FontSize set
Sets the fontsize.
Referenced by com.mxgraph.mxStencil.DrawElement().
FontStyle
int com.mxgraph.mxGdiCanvas2D.FontStyle set
Sets the given fontstyle.
Referenced by com.mxgraph.mxStencil.DrawElement().
LineCap
string com.mxgraph.mxGdiCanvas2D.LineCap set
Sets the linecap.
Referenced by com.mxgraph.mxStencil.DrawElement().
LineJoin
string com.mxgraph.mxGdiCanvas2D.LineJoin set
Sets the linejoin.
Referenced by com.mxgraph.mxStencil.DrawElement().
MiterLimit
double com.mxgraph.mxGdiCanvas2D.MiterLimit set
Sets the miterlimit.
Referenced by com.mxgraph.mxStencil.DrawElement().
Shadow
bool com.mxgraph.mxGdiCanvas2D.Shadow set
Default value mxConstants#NONE.
ShadowAlpha
double com.mxgraph.mxGdiCanvas2D.ShadowAlpha set
Default value 1. This method may add rendering overhead and should be used with care.
ShadowColor
string com.mxgraph.mxGdiCanvas2D.ShadowColor set
Default value mxConstants#NONE.
StrokeAlpha
double com.mxgraph.mxGdiCanvas2D.StrokeAlpha set
Sets the given alpha.
StrokeColor
string com.mxgraph.mxGdiCanvas2D.StrokeColor set
Caches color conversion as it is expensive.
Referenced by com.mxgraph.mxStencil.DrawElement(), and com.mxgraph.mxStencil.PaintShape().
StrokeWidth
double com.mxgraph.mxGdiCanvas2D.StrokeWidth set
Sets the strokewidth.
Referenced by com.mxgraph.mxStencil.DrawElement(), com.mxgraph.mxStencil.DrawShape(), and com.mxgraph.mxStencil.PaintShape().
The documentation for this class was generated from the following file:
src/canvas/mxGdiCanvas2D.cs