mxGraph: com.mxgraph.mxGdiCanvas Class Reference
com.mxgraph.mxGdiCanvas Class Reference
Implementation of a canvas that uses GDI for painting.
Public Member Functions
mxGdiCanvas ()
Constructs a new GDI canvas.
mxGdiCanvas (Graphics g)
Constructs a new GDI canvas for the given graphics instance.
override Object DrawCell (mxCellState state)
see com.mxgraph.mxICanvas.DrawCell()
override Object DrawLabel (string text, mxCellState state, bool html)
see com.mxgraph.mxICanvas.DrawLabel()
void DrawShape (int x, int y, int w, int h, Dictionary< string, Object > style)
Draws the shape specified with the STYLE_SHAPE key in the given style.
void DrawLine (List< mxPoint > pts, Dictionary< string, Object > style)
Draws the given lines as segments between all points of the given list of mxPoints.
mxPoint DrawMarker (Object type, mxPoint p0, mxPoint pe, float size, Pen pen)
Draws the given type of marker.
void DrawText (string text, int x, int y, int w, int h, Dictionary< string, Object > style)
Draws the specified text either using drawHtmlString or using drawString.
void Destroy ()
Destroys the canvas and frees all allocated resources.
Static Public Member Functions
static int getArcSize (int w, int h)
Computes the arc size for the given dimension.
Static Public Attributes
static bool PRESERVE_IMAGE_ASPECT = true
Specifies if image aspect should be preserved in drawImage.
Static Public Attributes inherited from com.mxgraph.mxBasicCanvas
static string DEFAULT_IMAGEBASEPATH = ""
Defines the default value for the imageBasePath in all GDI canvases. Default is an empty string.
Protected Member Functions
Image LoadImage (String image)
Returns an image instance for the given URL. If the URL has been loaded before than an instance of the same instance is returned as in the previous call.
void DrawGlassEffect (int x, int y, int w, int h, Dictionary< string, Object > style)
Draws the glass effect.
void DrawPolygon (Point[] polygon, Brush brush, Pen pen, bool shadow)
Draws a a polygon for the given parameters.
void DrawPath (GraphicsPath path, Brush brush, Pen pen, bool shadow)
Draws a path for the given parameters.
void DrawRect (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, bool rounded)
Draws a rectangle for the given parameters.
void DrawImage (int x, int y, int w, int h, String image)
Draws an image for the given parameters.
void DrawImage (int x, int y, int w, int h, String image, bool preserveAspect, bool flipH, bool flipV)
Draws an image for the given parameters.
void DrawOval (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow)
Draws an oval for the given parameters.
void DrawRhombus (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow)
Draws an rhombus (aka. diamond) for the given parameters.
void DrawCylinder (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow)
Draws a cylinder for the given parameters.
void DrawActor (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow)
Draws an actor shape for the given parameters.
void DrawCloud (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow)
Draws a cloud shape for the given parameters.
void DrawTriangle (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, string direction)
Draws a triangle shape for the given parameters.
void DrawHexagon (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, string direction)
Draws a hexagon shape for the given parameters.
Protected Member Functions inherited from com.mxgraph.mxBasicCanvas
string GetImageForStyle (Dictionary< string, Object > style)
Gets the image path from the given style. If the path is relative (does not start with a slash) then it is appended to the imageBasePath.
Protected Attributes
Dictionary< string, Image > imageCache = new Dictionary<string, Image>()
Cache for loading images.
Graphics g
Global graphics handle to the image.
Protected Attributes inherited from com.mxgraph.mxBasicCanvas
string imageBasePath = DEFAULT_IMAGEBASEPATH
Defines the base path for images with relative paths. Trailing slash is required. Default value is DEFAULT_IMAGEBASEPATH.
Point translate = new Point(0, 0)
Specifies the current translation. Default is (0,0).
double scale
Specifies the current scale. Default is 1.
bool drawLabels = true
Specifies whether labels should be painted. Default is true.
Properties
Graphics Graphics [get, set]
Sets or gets the graphics object to paint the canvas.
Properties inherited from com.mxgraph.mxBasicCanvas
Point Translate [get, set]
see com.mxgraph.mxICanvas.Translate
double Scale [get, set]
see com.mxgraph.mxICanvas.Scale
bool DrawLabels [get, set]
Sets if labels should be visible.
string ImageBasePath [get, set]
Sets or gets the image base path.
Properties inherited from com.mxgraph.mxICanvas
Point Translate [get, set]
Sets or returns the user object of the cell.
double Scale [get, set]
Sets or returns the user object of the cell.
Detailed Description
Implementation of a canvas that uses GDI for painting.
Constructor & Destructor Documentation
mxGdiCanvas() [1/2]
com.mxgraph.mxGdiCanvas.mxGdiCanvas () inline
Constructs a new GDI canvas.
mxGdiCanvas() [2/2]
com.mxgraph.mxGdiCanvas.mxGdiCanvas (Graphics g) inline
Constructs a new GDI canvas for the given graphics instance.
Member Function Documentation
Destroy()
void com.mxgraph.mxGdiCanvas.Destroy () inline
Destroys the canvas and frees all allocated resources.
DrawActor()
void com.mxgraph.mxGdiCanvas.DrawActor (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow) inline protected
Draws an actor shape for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
DrawCell()
override Object com.mxgraph.mxGdiCanvas.DrawCell (mxCellState state) inline virtual
see com.mxgraph.mxICanvas.DrawCell()
Implements com.mxgraph.mxBasicCanvas.
References com.mxgraph.mxCellState.AbsolutePointCount(), com.mxgraph.mxCellState.AbsolutePoints, com.mxgraph.mxConstants.DEFAULT_STARTSIZE, com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxRectangle.GetRectangle(), com.mxgraph.mxStencilRegistry.GetStencil(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxStencil.PaintShape(), com.mxgraph.mxConstants.SHAPE_SWIMLANE, com.mxgraph.mxCellState.Style, com.mxgraph.mxConstants.STYLE_FILLCOLOR, com.mxgraph.mxConstants.STYLE_GRADIENTCOLOR, com.mxgraph.mxConstants.STYLE_HORIZONTAL, com.mxgraph.mxConstants.STYLE_ROTATION, com.mxgraph.mxConstants.STYLE_ROUNDED, com.mxgraph.mxConstants.STYLE_SHAPE, com.mxgraph.mxConstants.STYLE_STARTSIZE, and com.mxgraph.mxConstants.STYLE_SWIMLANE_FILLCOLOR.
Referenced by com.mxgraph.mxImageCanvas.DrawCell().
DrawCloud()
void com.mxgraph.mxGdiCanvas.DrawCloud (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow) inline protected
Draws a cloud shape for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
DrawCylinder()
void com.mxgraph.mxGdiCanvas.DrawCylinder (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow) inline protected
Draws a cylinder for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
DrawGlassEffect()
void com.mxgraph.mxGdiCanvas.DrawGlassEffect (int x, int y, int w, int h, Dictionary< string, Object > style) inline protected
Draws the glass effect.
References com.mxgraph.mxUtils.GetFloat(), and com.mxgraph.mxConstants.STYLE_STROKEWIDTH.
DrawHexagon()
void com.mxgraph.mxGdiCanvas.DrawHexagon (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, string direction) inline protected
Draws a hexagon shape for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
direction Specifies the direction of the hexagon.
References com.mxgraph.mxConstants.DIRECTION_NORTH, and com.mxgraph.mxConstants.DIRECTION_SOUTH.
DrawImage() [1/2]
void com.mxgraph.mxGdiCanvas.DrawImage (int x, int y, int w, int h, String image) inline protected
Draws an image for the given parameters.
Parameters
x X-coordinate of the image.
y Y-coordinate of the image.
w Width of the image.
h Height of the image.
image URL of the image.
DrawImage() [2/2]
void com.mxgraph.mxGdiCanvas.DrawImage (int x, int y, int w, int h, String image, bool preserveAspect, bool flipH, bool flipV) inline protected
Draws an image for the given parameters.
Parameters
x X-coordinate of the image.
y Y-coordinate of the image.
w Width of the image.
h Height of the image.
image URL of the image.
DrawLabel()
override Object com.mxgraph.mxGdiCanvas.DrawLabel (string text, mxCellState state, bool html) inline virtual
see com.mxgraph.mxICanvas.DrawLabel()
Implements com.mxgraph.mxBasicCanvas.
References com.mxgraph.mxRectangle.GetRectangle(), com.mxgraph.mxCellState.LabelBounds, and com.mxgraph.mxCellState.Style.
Referenced by com.mxgraph.mxImageCanvas.DrawLabel().
DrawLine()
void com.mxgraph.mxGdiCanvas.DrawLine (List< mxPoint > pts, Dictionary< string, Object > style) inline
Draws the given lines as segments between all points of the given list of mxPoints.
Parameters
pts List of points that define the line.
style Style to be used for painting the line.
References com.mxgraph.mxConstants.ARROW_SIZE, com.mxgraph.mxConstants.ARROW_SPACING, com.mxgraph.mxConstants.ARROW_WIDTH, com.mxgraph.mxPoint.Clone(), com.mxgraph.mxConstants.DEFAULT_MARKERSIZE, com.mxgraph.mxConstants.DIRECTION_EAST, com.mxgraph.mxConstants.DIRECTION_NORTH, com.mxgraph.mxConstants.DIRECTION_SOUTH, com.mxgraph.mxConstants.DIRECTION_WEST, com.mxgraph.mxUtils.GetColor(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxConstants.LINE_ARCSIZE, com.mxgraph.mxConstants.SHAPE_ARROW, com.mxgraph.mxConstants.STYLE_DASHED, com.mxgraph.mxConstants.STYLE_ENDARROW, com.mxgraph.mxConstants.STYLE_ENDSIZE, com.mxgraph.mxConstants.STYLE_FILLCOLOR, com.mxgraph.mxConstants.STYLE_GRADIENT_DIRECTION, com.mxgraph.mxConstants.STYLE_GRADIENTCOLOR, com.mxgraph.mxConstants.STYLE_OPACITY, com.mxgraph.mxConstants.STYLE_ROUNDED, com.mxgraph.mxConstants.STYLE_SHADOW, com.mxgraph.mxConstants.STYLE_SHAPE, com.mxgraph.mxConstants.STYLE_STARTARROW, com.mxgraph.mxConstants.STYLE_STARTSIZE, com.mxgraph.mxConstants.STYLE_STROKECOLOR, com.mxgraph.mxConstants.STYLE_STROKEWIDTH, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
DrawMarker()
mxPoint com.mxgraph.mxGdiCanvas.DrawMarker (Object type, mxPoint p0, mxPoint pe, float size, Pen pen) inline
Draws the given type of marker.
Parameters
type
p0
pe
size
pen
Returns
References com.mxgraph.mxConstants.ARROW_BLOCK, com.mxgraph.mxConstants.ARROW_CLASSIC, com.mxgraph.mxConstants.ARROW_DIAMOND, com.mxgraph.mxConstants.ARROW_OPEN, com.mxgraph.mxConstants.ARROW_OVAL, com.mxgraph.mxPoint.Clone(), com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
DrawOval()
void com.mxgraph.mxGdiCanvas.DrawOval (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow) inline protected
Draws an oval for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
References com.mxgraph.mxConstants.SHADOW_OFFSETX, com.mxgraph.mxConstants.SHADOW_OFFSETY, and com.mxgraph.mxConstants.SHADOWCOLOR.
DrawPath()
void com.mxgraph.mxGdiCanvas.DrawPath (GraphicsPath path, Brush brush, Pen pen, bool shadow) inline protected
Draws a path for the given parameters.
Parameters
path Path object to be drawn.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
References com.mxgraph.mxConstants.SHADOW_OFFSETX, com.mxgraph.mxConstants.SHADOW_OFFSETY, and com.mxgraph.mxConstants.SHADOWCOLOR.
DrawPolygon()
void com.mxgraph.mxGdiCanvas.DrawPolygon (Point [] polygon, Brush brush, Pen pen, bool shadow) inline protected
Draws a a polygon for the given parameters.
Parameters
polygon Points of the polygon.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
References com.mxgraph.mxConstants.SHADOW_OFFSETX, com.mxgraph.mxConstants.SHADOW_OFFSETY, and com.mxgraph.mxConstants.SHADOWCOLOR.
DrawRect()
void com.mxgraph.mxGdiCanvas.DrawRect (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, bool rounded) inline protected
Draws a rectangle for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
rounded Boolean indicating if the rectangle is rounded.
References com.mxgraph.mxConstants.SHADOW_OFFSETX, com.mxgraph.mxConstants.SHADOW_OFFSETY, and com.mxgraph.mxConstants.SHADOWCOLOR.
DrawRhombus()
void com.mxgraph.mxGdiCanvas.DrawRhombus (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow) inline protected
Draws an rhombus (aka. diamond) for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
DrawShape()
void com.mxgraph.mxGdiCanvas.DrawShape (int x, int y, int w, int h, Dictionary< string, Object > style) inline
Draws the shape specified with the STYLE_SHAPE key in the given style.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
style Style of the the shape.
References com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, com.mxgraph.mxConstants.ALIGN_TOP, com.mxgraph.mxConstants.DEFAULT_IMAGESIZE, com.mxgraph.mxConstants.DIRECTION_EAST, com.mxgraph.mxConstants.DIRECTION_NORTH, com.mxgraph.mxConstants.DIRECTION_SOUTH, com.mxgraph.mxConstants.DIRECTION_WEST, com.mxgraph.mxUtils.GetColor(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxUtils.GetInt(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxConstants.SHAPE_ACTOR, com.mxgraph.mxConstants.SHAPE_CLOUD, com.mxgraph.mxConstants.SHAPE_CYLINDER, com.mxgraph.mxConstants.SHAPE_DOUBLE_ELLIPSE, com.mxgraph.mxConstants.SHAPE_ELLIPSE, com.mxgraph.mxConstants.SHAPE_HEXAGON, com.mxgraph.mxConstants.SHAPE_LABEL, com.mxgraph.mxConstants.SHAPE_LINE, com.mxgraph.mxConstants.SHAPE_RHOMBUS, com.mxgraph.mxConstants.SHAPE_TRIANGLE, com.mxgraph.mxConstants.STYLE_DASHED, com.mxgraph.mxConstants.STYLE_DIRECTION, com.mxgraph.mxConstants.STYLE_FILLCOLOR, com.mxgraph.mxConstants.STYLE_GLASS, com.mxgraph.mxConstants.STYLE_GRADIENT_DIRECTION, com.mxgraph.mxConstants.STYLE_GRADIENTCOLOR, com.mxgraph.mxConstants.STYLE_IMAGE, com.mxgraph.mxConstants.STYLE_IMAGE_ALIGN, com.mxgraph.mxConstants.STYLE_IMAGE_BACKGROUND, com.mxgraph.mxConstants.STYLE_IMAGE_BORDER, com.mxgraph.mxConstants.STYLE_IMAGE_FLIPH, com.mxgraph.mxConstants.STYLE_IMAGE_FLIPV, com.mxgraph.mxConstants.STYLE_IMAGE_HEIGHT, com.mxgraph.mxConstants.STYLE_IMAGE_VERTICAL_ALIGN, com.mxgraph.mxConstants.STYLE_IMAGE_WIDTH, com.mxgraph.mxConstants.STYLE_OPACITY, com.mxgraph.mxConstants.STYLE_ROUNDED, com.mxgraph.mxConstants.STYLE_SHADOW, com.mxgraph.mxConstants.STYLE_SHAPE, com.mxgraph.mxConstants.STYLE_SPACING, com.mxgraph.mxConstants.STYLE_STROKECOLOR, and com.mxgraph.mxConstants.STYLE_STROKEWIDTH.
DrawText()
void com.mxgraph.mxGdiCanvas.DrawText (string text, int x, int y, int w, int h, Dictionary< string, Object > style) inline
Draws the specified text either using drawHtmlString or using drawString.
Parameters
text
x X-coordinate of the text.
y Y-coordinate of the text.
w Width of the text.
h Height of the text.
style Style to be used for painting the text.
References com.mxgraph.mxUtils.GetColor(), com.mxgraph.mxUtils.GetFloat(), com.mxgraph.mxUtils.GetFont(), com.mxgraph.mxUtils.GetStringFormat(), com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxConstants.STYLE_FONTCOLOR, com.mxgraph.mxConstants.STYLE_HORIZONTAL, com.mxgraph.mxConstants.STYLE_LABEL_BACKGROUNDCOLOR, com.mxgraph.mxConstants.STYLE_LABEL_BORDERCOLOR, and com.mxgraph.mxConstants.STYLE_OPACITY.
DrawTriangle()
void com.mxgraph.mxGdiCanvas.DrawTriangle (int x, int y, int w, int h, Brush brush, Pen pen, bool shadow, string direction) inline protected
Draws a triangle shape for the given parameters.
Parameters
x X-coordinate of the shape.
y Y-coordinate of the shape.
w Width of the shape.
h Height of the shape.
brush Optional brush for painting the background.
pen Optional pen for painting the border.
shadow Boolean indicating if a shadow should be painted.
direction Specifies the direction of the triangle.
References com.mxgraph.mxConstants.DIRECTION_NORTH, com.mxgraph.mxConstants.DIRECTION_SOUTH, and com.mxgraph.mxConstants.DIRECTION_WEST.
getArcSize()
static int com.mxgraph.mxGdiCanvas.getArcSize (int w, int h) inline static
Computes the arc size for the given dimension.
Parameters
w Width of the rectangle.
h Height of the rectangle.
Returns
Returns the arc size for the given dimension.
LoadImage()
Image com.mxgraph.mxGdiCanvas.LoadImage (String image) inline protected
Returns an image instance for the given URL. If the URL has been loaded before than an instance of the same instance is returned as in the previous call.
References com.mxgraph.mxUtils.LoadImage().
Member Data Documentation
g
Graphics com.mxgraph.mxGdiCanvas.g protected
Global graphics handle to the image.
imageCache
Dictionary<string, Image> com.mxgraph.mxGdiCanvas.imageCache = new Dictionary<string, Image>() protected
Cache for loading images.
PRESERVE_IMAGE_ASPECT
bool com.mxgraph.mxGdiCanvas.PRESERVE_IMAGE_ASPECT = true static
Specifies if image aspect should be preserved in drawImage.
Property Documentation
Graphics
Graphics com.mxgraph.mxGdiCanvas.Graphics get set
Sets or gets the graphics object to paint the canvas.
Referenced by com.mxgraph.mxStencil.CreateCanvas(), com.mxgraph.mxImageCanvas.Destroy(), and com.mxgraph.mxImageCanvas.mxImageCanvas().
The documentation for this class was generated from the following file:
src/canvas/mxGdiCanvas.cs