mxGraph: com.mxgraph.mxUtils Class Reference
com.mxgraph.mxUtils Class Reference
Contains various helper methods for use with mxGraph.
Public Member Functions
String AddStylename (String style, String stylename)
Adds the specified stylename to the given style if it does not already contain the stylename.
String RemoveStylename (String style, String stylename)
Removes all occurrences of the specified stylename in the given style and returns the updated style.
Static Public Member Functions
static mxRectangle GetLabelSize (string label, Dictionary< string, Object > style, int width)
Returns the size of the given label.
static mxRectangle GetLabelPaintBounds (String label, Dictionary< string, Object > style, bool isHtml, mxPoint offset, mxRectangle vertexBounds, double scale)
Returns the paint bounds for the given label.
static mxRectangle GetScaledLabelBounds (double x, double y, mxRectangle size, double outerWidth, double outerHeight, Dictionary< string, Object > style, double scale)
Returns the bounds for a label for the given location and size, taking into account the alignment and spacing in the specified style, as well as the width and height of the rectangle that contains the label. (For edge labels this width and height is 0.) The scale is used to scale the given size and the spacings in the specified style.
static mxRectangle GetSizeForString (String text, Font font)
Returns the size of the given text.
static mxRectangle GetSizeForString (String text, Font font, int width)
Returns an mxRectangle with the size (width and height in pixels) of the given text.
static double ToRadians (double deg)
Converts the given degree to radians.
static double [] ArcToCurves (double x0, double y0, double r1, double r2, double angle, double largeArcFlag, double sweepFlag, double x, double y)
Converts the given arc to a series of curves.
static mxRectangle GetBoundingBox (mxRectangle rect, double rotation)
Returns the bounding box of the rotated rectangle.
static mxPoint GetRotatedPoint (mxPoint pt, double cos, double sin)
Rotates the given point by the given cos and sin.
static mxPoint GetRotatedPoint (mxPoint pt, double cos, double sin, mxPoint c)
Rotates the given point by the given cos and sin.
static void FillClippedRect (Graphics g, Brush brush, int x, int y, int width, int height)
static Image CreateImage (int width, int height, Color? background)
Creates an image for the given parameters.
static List< mxPoint > TranslatePoints (List< mxPoint > pts, double dx, double dy)
Creates a new list of new points obtained by translating the points in the given list by the given vector. Elements that are not mxPoints are added to the result as-is.
static mxPoint Intersection (double x0, double y0, double x1, double y1, double x2, double y2, double x3, double y3)
Returns the intersection of two lines as an mxPoint.
static String GetStylename (String style)
Returns the stylename in a style of the form stylename[;key=value] or an empty string if the given style does not contain a stylename.
static String [] GetStylenames (String style)
Returns the stylenames in a style of the form stylename[;key=value] or an empty array if the given style does not contain any stylenames.
static int IndexOfStylename (String style, String stylename)
Returns the index of the given stylename in the given style. This returns -1 if the given stylename does not occur (as a stylename) in the given style, otherwise it returns the index of the first character.
static String RemoveAllStylenames (String style)
Removes all stylenames from the given style and returns the updated style.
static void SetCellStyles (mxIGraphModel model, Object[] cells, String key, String value)
Assigns the value for the given key in the styles of the given cells, or removes the key from the styles if the value is null.
static String SetStyle (String style, String key, String value)
Adds or removes the given key, value pair to the style and returns the new style. If value is null or zero length then the key is removed from the style.
static void SetCellStyleFlags (mxIGraphModel model, Object[] cells, String key, int flag, Boolean value)
Sets or toggles the flag bit for the given key in the cell's styles. If value is null then the flag is toggled.
static String SetStyleFlag (String style, String key, int flag, bool? value)
Sets or removes the given key from the specified style and returns the new style. If value is null then the flag is toggled.
static bool IsTrue (Dictionary< string, Object > dict, string key)
Returns true if the dictionary contains true for the given key or false if no value is defined for the key.
static bool IsTrue (Dictionary< string, Object > dict, string key, bool defaultValue)
Returns true if the dictionary contains true for the given key or the given default value if no value is defined for the key.
static int GetInt (Dictionary< string, Object > dict, string key)
Returns the value for key in dictionary as an int or 0 if no value is defined for the key.
static int GetInt (Dictionary< string, Object > dict, string key, int defaultValue)
Returns the value for key in dictionary as an int or the given default value if no value is defined for the key.
static float GetFloat (Dictionary< string, Object > dict, string key)
Returns the value for key in dictionary as a float or 0 if no value is defined for the key.
static float GetFloat (Dictionary< string, Object > dict, string key, float defaultValue)
Returns the value for key in dictionary as a float or the given default value if no value is defined for the key.
static double GetDouble (Dictionary< string, Object > dict, string key)
Returns the value for key in dictionary as a double or 0 if no value is defined for the key.
static double GetDouble (Dictionary< string, Object > dict, string key, double defaultValue)
Returns the value for key in dictionary as a double or the given default value if no value is defined for the key.
static string GetString (Dictionary< string, Object > dict, string key)
Returns the value for key in dictionary as a string or null if no value is defined for the key.
static string GetString (Dictionary< string, Object > dict, string key, string defaultValue)
Returns the value for key in dictionary as a string or the given default value if no value is defined for the key.
static Color GetColor (Dictionary< string, Object > dict, string key)
Returns the value for key in dictionary as a color or null if no value is defined for the key.
static Color GetColor (Dictionary< string, Object > dict, string key, Color? defaultValue)
Returns the value for key in dictionary as a color or the given default value if no value is defined for the key.
static Font GetFont (Dictionary< string, Object > style)
static Font GetFont (Dictionary< string, Object > style, double scale)
static StringFormat GetStringFormat (Dictionary< string, Object > style)
Creates a new StringFormat object for the given style.
static string ReadFile (string filename)
Reads the given filename into a string.
static string GetMd5Hash (string text)
Returns the Md5 hash for the given text.
static bool IsNode (Object value, String nodeName)
Returns true if the given value is an XML node with the specified nodename. specified.
static bool IsNode (Object value, String nodeName, String attributeName, String attributeValue)
Returns true if the user object is an XML node with the specified type and and the optional attribute has the specified value or is not specified.
static Image LoadImage (String url)
Loads an image from the local filesystem, a data URI or any other URL.
static XmlDocument CreateDocument ()
Returns a new, empty DOM document. External entities and DTDs are ignored.
static XmlDocument LoadDocument (string uri)
Returns a new DOM document for the given URI.
static XmlDocument ParseXml (string xml)
Returns a document that represents the given XML string.
static XmlNode FindNode (XmlNode node, String attr, String value)
Returns the first node where attr equals value. This implementation does not use XPath.
static Object Eval (string expression)
Evaluates a Java expression to a class member using mxCodecRegistry. The range of supported expressions is limited to static class members such as mxEdgeStyle.ElbowConnector.
static String HtmlEntities (String text)
Converts the ampersand, quote, prime, less-than and greater-than characters to their corresponding HTML entities in the given string.
static string GetXml (XmlNode node)
Returns a string that represents the given node.
static string GetPrettyXml (XmlNode node)
Returns a pretty-printed XML string for the given node.
static string GetXml (XmlNode node, Formatting formatting)
Returns a pretty-printed XML string for the given node.
Detailed Description
Contains various helper methods for use with mxGraph.
Member Function Documentation
AddStylename()
String com.mxgraph.mxUtils.AddStylename (String style, String stylename) inline
Adds the specified stylename to the given style if it does not already contain the stylename.
Parameters
style
stylename
Returns
ArcToCurves()
static double [] com.mxgraph.mxUtils.ArcToCurves (double x0, double y0, double r1, double r2, double angle, double largeArcFlag, double sweepFlag, double x, double y) inline static
Converts the given arc to a series of curves.
Parameters
x0
y0
r1
r2
angle
largeArcFlag
sweepFlag
x
y
Returns
Referenced by com.mxgraph.mxStencil.DrawElement().
CreateDocument()
static XmlDocument com.mxgraph.mxUtils.CreateDocument () inline static
Returns a new, empty DOM document. External entities and DTDs are ignored.
Returns
Returns a new DOM document.
Referenced by com.mxgraph.mxCodec.mxCodec().
CreateImage()
static Image com.mxgraph.mxUtils.CreateImage (int width, int height, Color? background) inline static
Creates an image for the given parameters.
Parameters
width
height
background
Returns
Referenced by com.mxgraph.mxImageCanvas.mxImageCanvas().
Eval()
static Object com.mxgraph.mxUtils.Eval (string expression) inline static
Evaluates a Java expression to a class member using mxCodecRegistry. The range of supported expressions is limited to static class members such as mxEdgeStyle.ElbowConnector.
Parameters
expression
Returns
References com.mxgraph.mxCodecRegistry.GetTypeForName().
Referenced by com.mxgraph.mxStylesheetCodec.Decode(), com.mxgraph.mxGraphView.GetEdgeStyle(), and com.mxgraph.mxGraphView.GetPerimeterFunction().
FillClippedRect()
static void com.mxgraph.mxUtils.FillClippedRect (Graphics g, Brush brush, int x, int y, int width, int height) inline static
Parameters
g
brush
x
y
width
height
FindNode()
static XmlNode com.mxgraph.mxUtils.FindNode (XmlNode node, String attr, String value) inline static
Returns the first node where attr equals value. This implementation does not use XPath.
GetBoundingBox()
static mxRectangle com.mxgraph.mxUtils.GetBoundingBox (mxRectangle rect, double rotation) inline static
Returns the bounding box of the rotated rectangle.
References com.mxgraph.mxRectangle.Add(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxGraphView.UpdateBoundingBox().
GetColor() [1/2]
static Color com.mxgraph.mxUtils.GetColor (Dictionary< string, Object > dict, string key) inline static
Returns the value for key in dictionary as a color or null if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the color value for key in dict.
Referenced by com.mxgraph.mxGdiCanvas.DrawLine(), com.mxgraph.mxGdiCanvas.DrawShape(), and com.mxgraph.mxGdiCanvas.DrawText().
GetColor() [2/2]
static Color com.mxgraph.mxUtils.GetColor (Dictionary< string, Object > dict, string key, Color? defaultValue) inline static
Returns the value for key in dictionary as a color or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the color value for key in dict.
GetDouble() [1/2]
static double com.mxgraph.mxUtils.GetDouble (Dictionary< string, Object > dict, string key) inline static
Returns the value for key in dictionary as a double or 0 if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the double value for key in dict.
Referenced by com.mxgraph.mxGraphViewImageReader.CreateCanvas(), com.mxgraph.mxGdiCanvas.DrawCell(), com.mxgraph.mxStencil.DrawShape(), com.mxgraph.mxGraph.GetConnectionConstraint(), com.mxgraph.mxUtils.GetLabelPaintBounds(), com.mxgraph.mxGraphView.GetPerimeterBounds(), com.mxgraph.mxGraph.HitsSwimlaneContent(), com.mxgraph.mxStencil.PaintShape(), com.mxgraph.mxGraphViewReader.ParseElement(), com.mxgraph.mxGraphViewReader.ParseState(), com.mxgraph.mxGraphView.UpdateBoundingBox(), and com.mxgraph.mxGraphView.UpdateFloatingTerminalPoint().
GetDouble() [2/2]
static double com.mxgraph.mxUtils.GetDouble (Dictionary< string, Object > dict, string key, double defaultValue) inline static
Returns the value for key in dictionary as a double or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the double value for key in dict.
GetFloat() [1/2]
static float com.mxgraph.mxUtils.GetFloat (Dictionary< string, Object > dict, string key) inline static
Returns the value for key in dictionary as a float or 0 if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the float value for key in dict.
Referenced by com.mxgraph.mxGdiCanvas.DrawCell(), com.mxgraph.mxGdiCanvas.DrawGlassEffect(), com.mxgraph.mxGdiCanvas.DrawLine(), com.mxgraph.mxGdiCanvas.DrawShape(), com.mxgraph.mxGdiCanvas.DrawText(), com.mxgraph.mxGraphView.GetRoutingCenterX(), and com.mxgraph.mxGraphView.GetRoutingCenterY().
GetFloat() [2/2]
static float com.mxgraph.mxUtils.GetFloat (Dictionary< string, Object > dict, string key, float defaultValue) inline static
Returns the value for key in dictionary as a float or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the float value for key in dict.
GetFont() [1/2]
static Font com.mxgraph.mxUtils.GetFont (Dictionary< string, Object > style) inline static
Parameters
style
Returns
Referenced by com.mxgraph.mxGdiCanvas.DrawText().
GetFont() [2/2]
static Font com.mxgraph.mxUtils.GetFont (Dictionary< string, Object > style, double scale) inline static
Parameters
style
scale
Returns
References com.mxgraph.mxConstants.DEFAULT_FONTFAMILY, com.mxgraph.mxConstants.DEFAULT_FONTSIZE, com.mxgraph.mxConstants.FONT_BOLD, com.mxgraph.mxConstants.FONT_ITALIC, com.mxgraph.mxConstants.FONT_SIZEFACTOR, com.mxgraph.mxConstants.FONT_UNDERLINE, com.mxgraph.mxConstants.STYLE_FONTFAMILY, com.mxgraph.mxConstants.STYLE_FONTSIZE, and com.mxgraph.mxConstants.STYLE_FONTSTYLE.
GetInt() [1/2]
static int com.mxgraph.mxUtils.GetInt (Dictionary< string, Object > dict, string key) inline static
Returns the value for key in dictionary as an int or 0 if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the integer value for key in dict.
Referenced by com.mxgraph.mxGdiCanvas.DrawShape(), and com.mxgraph.mxGraphView.UpdateBoundingBox().
GetInt() [2/2]
static int com.mxgraph.mxUtils.GetInt (Dictionary< string, Object > dict, string key, int defaultValue) inline static
Returns the value for key in dictionary as an int or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the integer value for key in dict.
GetLabelPaintBounds()
static mxRectangle com.mxgraph.mxUtils.GetLabelPaintBounds (String label, Dictionary< string, Object > style, bool isHtml, mxPoint offset, mxRectangle vertexBounds, double scale) inline static
Returns the paint bounds for the given label.
Returns
References com.mxgraph.mxConstants.DEFAULT_STARTSIZE, com.mxgraph.mxRectangle.Equals(), com.mxgraph.mxUtils.GetDouble(), com.mxgraph.mxUtils.GetLabelSize(), com.mxgraph.mxUtils.GetScaledLabelBounds(), com.mxgraph.mxUtils.GetString(), com.mxgraph.mxRectangle.Height, com.mxgraph.mxUtils.IsTrue(), com.mxgraph.mxConstants.SHAPE_SWIMLANE, com.mxgraph.mxConstants.STYLE_HORIZONTAL, com.mxgraph.mxConstants.STYLE_SHAPE, com.mxgraph.mxConstants.STYLE_STARTSIZE, com.mxgraph.mxConstants.STYLE_WHITE_SPACE, com.mxgraph.mxRectangle.Width, com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
Referenced by com.mxgraph.mxGraphViewReader.ParseState(), and com.mxgraph.mxGraphView.UpdateLabelBounds().
GetLabelSize()
static mxRectangle com.mxgraph.mxUtils.GetLabelSize (string label, Dictionary< string, Object > style, int width) inline static
Returns the size of the given label.
Referenced by com.mxgraph.mxUtils.GetLabelPaintBounds().
GetMd5Hash()
static string com.mxgraph.mxUtils.GetMd5Hash (string text) inline static
Returns the Md5 hash for the given text.
Parameters
text String whose Md5 hash should be returned.
Returns
Returns the Md5 hash for the given text.
GetPrettyXml()
static string com.mxgraph.mxUtils.GetPrettyXml (XmlNode node) inline static
Returns a pretty-printed XML string for the given node.
Parameters
node Node to return the XML for.
Returns
Returns a formatted XML string.
GetRotatedPoint() [1/2]
static mxPoint com.mxgraph.mxUtils.GetRotatedPoint (mxPoint pt, double cos, double sin) inline static
Rotates the given point by the given cos and sin.
Referenced by com.mxgraph.mxStencil.DrawShadow().
GetRotatedPoint() [2/2]
static mxPoint com.mxgraph.mxUtils.GetRotatedPoint (mxPoint pt, double cos, double sin, mxPoint c) inline static
Rotates the given point by the given cos and sin.
References com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
GetScaledLabelBounds()
static mxRectangle com.mxgraph.mxUtils.GetScaledLabelBounds (double x, double y, mxRectangle size, double outerWidth, double outerHeight, Dictionary< string, Object > style, double scale) inline static
Returns the bounds for a label for the given location and size, taking into account the alignment and spacing in the specified style, as well as the width and height of the rectangle that contains the label. (For edge labels this width and height is 0.) The scale is used to scale the given size and the spacings in the specified style.
References com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, com.mxgraph.mxRectangle.Height, com.mxgraph.mxConstants.LABEL_INSET, com.mxgraph.mxConstants.STYLE_ALIGN, com.mxgraph.mxConstants.STYLE_HORIZONTAL, com.mxgraph.mxConstants.STYLE_SPACING, com.mxgraph.mxConstants.STYLE_SPACING_BOTTOM, com.mxgraph.mxConstants.STYLE_SPACING_LEFT, com.mxgraph.mxConstants.STYLE_SPACING_RIGHT, com.mxgraph.mxConstants.STYLE_SPACING_TOP, com.mxgraph.mxConstants.STYLE_VERTICAL_ALIGN, and com.mxgraph.mxRectangle.Width.
Referenced by com.mxgraph.mxUtils.GetLabelPaintBounds().
GetSizeForString() [1/2]
static mxRectangle com.mxgraph.mxUtils.GetSizeForString (String text, Font font) inline static
Returns the size of the given text.
Parameters
text String whose size should be returned.
font Specifies the font that should be used.
Returns
Returns the size of the given text.
GetSizeForString() [2/2]
static mxRectangle com.mxgraph.mxUtils.GetSizeForString (String text, Font font, int width) inline static
Returns an mxRectangle with the size (width and height in pixels) of the given text.
Parameters
text String whose size should be returned.
font Specifies the font that should be used.
width Specifies the width of the text block for word wrapping.
Returns
Returns the size of the given text.
GetString() [1/2]
static string com.mxgraph.mxUtils.GetString (Dictionary< string, Object > dict, string key) inline static
Returns the value for key in dictionary as a string or null if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the string value for key in dict.
Referenced by com.mxgraph.mxGdiCanvas.DrawCell(), com.mxgraph.mxGdiCanvas.DrawLine(), com.mxgraph.mxGdiCanvas.DrawShape(), com.mxgraph.mxStencil.DrawShape(), com.mxgraph.mxGraph.DrawState(), com.mxgraph.mxBasicCanvas.GetImageForStyle(), com.mxgraph.mxUtils.GetLabelPaintBounds(), com.mxgraph.mxUtils.GetStringFormat(), com.mxgraph.mxGraphView.GetTerminalPort(), com.mxgraph.mxGraph.IsSwimlane(), com.mxgraph.mxStencil.PaintShape(), com.mxgraph.mxGraphViewReader.ParseState(), com.mxgraph.mxGraph.PostProcessCellStyle(), com.mxgraph.mxGraphView.UpdateBoundingBox(), com.mxgraph.mxGraphView.UpdateLabelBounds(), and com.mxgraph.mxGraphView.UpdateVertexLabelOffset().
GetString() [2/2]
static string com.mxgraph.mxUtils.GetString (Dictionary< string, Object > dict, string key, string defaultValue) inline static
Returns the value for key in dictionary as a string or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the string value for key in dict.
GetStringFormat()
static StringFormat com.mxgraph.mxUtils.GetStringFormat (Dictionary< string, Object > style) inline static
Creates a new StringFormat object for the given style.
Parameters
style
Returns
References com.mxgraph.mxConstants.ALIGN_BOTTOM, com.mxgraph.mxConstants.ALIGN_CENTER, com.mxgraph.mxConstants.ALIGN_LEFT, com.mxgraph.mxConstants.ALIGN_MIDDLE, com.mxgraph.mxConstants.ALIGN_RIGHT, com.mxgraph.mxConstants.ALIGN_TOP, com.mxgraph.mxUtils.GetString(), com.mxgraph.mxConstants.STYLE_ALIGN, com.mxgraph.mxConstants.STYLE_VERTICAL_ALIGN, and com.mxgraph.mxConstants.STYLE_WHITE_SPACE.
Referenced by com.mxgraph.mxGdiCanvas.DrawText().
GetStylename()
static String com.mxgraph.mxUtils.GetStylename (String style) inline static
Returns the stylename in a style of the form stylename[;key=value] or an empty string if the given style does not contain a stylename.
Parameters
style String of the form stylename[;key=value].
Returns
Returns the stylename from the given formatted string.
GetStylenames()
static String [] com.mxgraph.mxUtils.GetStylenames (String style) inline static
Returns the stylenames in a style of the form stylename[;key=value] or an empty array if the given style does not contain any stylenames.
Parameters
style String of the form stylename[;stylename][;key=value].
Returns
Returns the stylename from the given formatted string.
GetXml() [1/2]
static string com.mxgraph.mxUtils.GetXml (XmlNode node) inline static
Returns a string that represents the given node.
Parameters
node Node to return the XML for.
Returns
Returns an XML string.
GetXml() [2/2]
static string com.mxgraph.mxUtils.GetXml (XmlNode node, Formatting formatting) inline static
Returns a pretty-printed XML string for the given node.
Parameters
node Node to return the XML for.
formatting Formatting of the string to be returned.
Returns
Returns a formatted XML string.
HtmlEntities()
static String com.mxgraph.mxUtils.HtmlEntities (String text) inline static
Converts the ampersand, quote, prime, less-than and greater-than characters to their corresponding HTML entities in the given string.
Parameters
text
Returns
IndexOfStylename()
static int com.mxgraph.mxUtils.IndexOfStylename (String style, String stylename) inline static
Returns the index of the given stylename in the given style. This returns -1 if the given stylename does not occur (as a stylename) in the given style, otherwise it returns the index of the first character.
Parameters
style
stylename
Returns
Intersection()
static mxPoint com.mxgraph.mxUtils.Intersection (double x0, double y0, double x1, double y1, double x2, double y2, double x3, double y3) inline static
Returns the intersection of two lines as an mxPoint.
Parameters
x0 X-coordinate of the first line's startpoint.
y0 Y-coordinate of the first line's startpoint.
x1 X-coordinate of the first line's endpoint.
y1 Y-coordinate of the first line's endpoint.
x2 X-coordinate of the second line's startpoint.
y2 Y-coordinate of the second line's startpoint.
x3 X-coordinate of the second line's endpoint.
y3 Y-coordinate of the second line's endpoint.
Returns
IsNode() [1/2]
static bool com.mxgraph.mxUtils.IsNode (Object value, String nodeName) inline static
Returns true if the given value is an XML node with the specified nodename. specified.
Parameters
value Object that represents the value to be tested.
nodeName String that specifies the node name.
Returns
Returns true if the node name of the user object is equal to the given type.
IsNode() [2/2]
static bool com.mxgraph.mxUtils.IsNode (Object value, String nodeName, String attributeName, String attributeValue) inline static
Returns true if the user object is an XML node with the specified type and and the optional attribute has the specified value or is not specified.
Parameters
value Object that represents the value to be tested.
nodeName String that specifies the node name.
attributeName Optional attribute name to check.
attributeValue Optional attribute value to check.
Returns
Returns true if the cell matches the given conditions.
IsTrue() [1/2]
static bool com.mxgraph.mxUtils.IsTrue (Dictionary< string, Object > dict, string key) inline static
Returns true if the dictionary contains true for the given key or false if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
Returns
Returns the boolean value for key in dict.
Referenced by com.mxgraph.mxGdiCanvas.DrawCell(), com.mxgraph.mxGdiCanvas.DrawLine(), com.mxgraph.mxGdiCanvas.DrawShape(), com.mxgraph.mxGdiCanvas.DrawText(), com.mxgraph.mxGraph.GetConnectionConstraint(), com.mxgraph.mxGraphView.GetEdgeStyle(), com.mxgraph.mxGraph.GetLabel(), com.mxgraph.mxUtils.GetLabelPaintBounds(), com.mxgraph.mxGraph.HitsSwimlaneContent(), com.mxgraph.mxGraph.IsOrthogonal(), com.mxgraph.mxStencil.PaintShape(), com.mxgraph.mxGraphViewReader.ParseState(), and com.mxgraph.mxGraphView.UpdateBoundingBox().
IsTrue() [2/2]
static bool com.mxgraph.mxUtils.IsTrue (Dictionary< string, Object > dict, string key, bool defaultValue) inline static
Returns true if the dictionary contains true for the given key or the given default value if no value is defined for the key.
Parameters
dict Dictionary that contains the key, value pairs.
key Key whose value should be returned.
defaultValue Default value to return if the key is undefined.
Returns
Returns the boolean value for key in dict.
LoadDocument()
static XmlDocument com.mxgraph.mxUtils.LoadDocument (string uri) inline static
Returns a new DOM document for the given URI.
Parameters
uri URI to parse into the document.
Returns
Returns a new DOM document for the given URI.
Referenced by com.mxgraph.mxObjectCodec.ProcessInclude().
LoadImage()
static Image com.mxgraph.mxUtils.LoadImage (String url) inline static
Loads an image from the local filesystem, a data URI or any other URL.
Referenced by com.mxgraph.mxGdiCanvas.LoadImage(), and com.mxgraph.mxGdiCanvas2D.LoadImage().
ParseXml()
static XmlDocument com.mxgraph.mxUtils.ParseXml (string xml) inline static
Returns a document that represents the given XML string.
Parameters
xml String that contains the XML markup.
Returns
Returns an XML document.
ReadFile()
static string com.mxgraph.mxUtils.ReadFile (string filename) inline static
Reads the given filename into a string.
Parameters
filename Name of the file to be read.
Returns
Returns a string representing the file contents.
RemoveAllStylenames()
static String com.mxgraph.mxUtils.RemoveAllStylenames (String style) inline static
Removes all stylenames from the given style and returns the updated style.
Parameters
style
Returns
RemoveStylename()
String com.mxgraph.mxUtils.RemoveStylename (String style, String stylename) inline
Removes all occurrences of the specified stylename in the given style and returns the updated style.
Parameters
style
stylename
Returns
SetCellStyleFlags()
static void com.mxgraph.mxUtils.SetCellStyleFlags (mxIGraphModel model, Object [] cells, String key, int flag, Boolean value) inline static
Sets or toggles the flag bit for the given key in the cell's styles. If value is null then the flag is toggled.
Parameters
model Model that contains the cells.
cells Array of cells to change the style for.
key Key of the style to be changed.
flag Integer for the bit to be changed.
value Optional boolean value for the flag.
References com.mxgraph.mxIGraphModel.BeginUpdate(), com.mxgraph.mxIGraphModel.EndUpdate(), com.mxgraph.mxIGraphModel.GetStyle(), and com.mxgraph.mxIGraphModel.SetStyle().
SetCellStyles()
static void com.mxgraph.mxUtils.SetCellStyles (mxIGraphModel model, Object [] cells, String key, String value) inline static
Assigns the value for the given key in the styles of the given cells, or removes the key from the styles if the value is null.
Parameters
model Model to execute the transaction in.
cells Array of cells to be updated.
key Key of the style to be changed.
value New value for the given key.
References com.mxgraph.mxIGraphModel.BeginUpdate(), com.mxgraph.mxIGraphModel.EndUpdate(), com.mxgraph.mxIGraphModel.GetStyle(), and com.mxgraph.mxIGraphModel.SetStyle().
Referenced by com.mxgraph.mxGraph.SetCellStyles().
SetStyle()
static String com.mxgraph.mxUtils.SetStyle (String style, String key, String value) inline static
Adds or removes the given key, value pair to the style and returns the new style. If value is null or zero length then the key is removed from the style.
Parameters
style String of the form stylename[;key=value].
key Key of the style to be changed.
value New value for the given key.
Returns
Returns the new style.
SetStyleFlag()
static String com.mxgraph.mxUtils.SetStyleFlag (String style, String key, int flag, bool? value) inline static
Sets or removes the given key from the specified style and returns the new style. If value is null then the flag is toggled.
Parameters
style String of the form stylename[;key=value].
key Key of the style to be changed.
flag Integer for the bit to be changed.
value Optional boolean value for the given flag.
Returns
Returns the new style.
ToRadians()
static double com.mxgraph.mxUtils.ToRadians (double deg) inline static
Converts the given degree to radians.
TranslatePoints()
static List<mxPoint> com.mxgraph.mxUtils.TranslatePoints (List< mxPoint > pts, double dx, double dy) inline static
Creates a new list of new points obtained by translating the points in the given list by the given vector. Elements that are not mxPoints are added to the result as-is.
Parameters
pts
dx
dy
Returns
References com.mxgraph.mxPoint.Clone(), com.mxgraph.mxPoint.X, and com.mxgraph.mxPoint.Y.
The documentation for this class was generated from the following file:
src/utils/mxUtils.cs