mxGraph: com.mxgraph.mxSaxOutputHandler Class Reference
com.mxgraph.mxSaxOutputHandler Class Reference
Public Member Functions
delegate void ElementHandler (Dictionary< string, string > atts)
Defines the requirements for an object that parses a node.
mxSaxOutputHandler (mxICanvas2D canvas)
Constructs a new sax output handler for the given canvas.
void Read (XmlReader reader)
Reads the given display XML data and parses all elements.
void ParseElement (string tagName, Dictionary< string, string > atts)
Parses the given element and paints it onto the canvas.
Protected Member Functions
string GetString (Dictionary< string, string > atts, string key)
string GetString (Dictionary< string, string > atts, string key, string defaultValue)
double GetDouble (Dictionary< string, string > atts, string key)
double GetDouble (Dictionary< string, string > atts, string key, double defaultValue)
int GetInt (Dictionary< string, string > atts, string key)
int GetInt (Dictionary< string, string > atts, string key, int defaultValue)
bool IsTrue (Dictionary< string, string > atts, string key)
bool IsTrue (Dictionary< string, string > atts, string key, bool defaultValue)
void InitHandlers ()
Protected Attributes
mxICanvas2D canvas
Holds the current canvas.
Dictionary< string, ElementHandler > handlers = new Dictionary<string, ElementHandler>()
Holds the handlers for specific XML nodes.
Properties
mxICanvas2D Canvas [get, set]
Sets or returns the current canvas.
Constructor & Destructor Documentation
mxSaxOutputHandler()
com.mxgraph.mxSaxOutputHandler.mxSaxOutputHandler (mxICanvas2D canvas) inline
Constructs a new sax output handler for the given canvas.
Member Function Documentation
ElementHandler()
delegate void com.mxgraph.mxSaxOutputHandler.ElementHandler (Dictionary< string, string > atts)
Defines the requirements for an object that parses a node.
InitHandlers()
void com.mxgraph.mxSaxOutputHandler.InitHandlers () inline protected
References com.mxgraph.mxICanvas2D.Alpha, com.mxgraph.mxICanvas2D.Begin(), com.mxgraph.mxICanvas2D.Close(), com.mxgraph.mxICanvas2D.CurveTo(), com.mxgraph.mxICanvas2D.Dashed, com.mxgraph.mxICanvas2D.DashPattern, com.mxgraph.mxICanvas2D.Ellipse(), com.mxgraph.mxICanvas2D.Fill(), com.mxgraph.mxICanvas2D.FillAlpha, com.mxgraph.mxICanvas2D.FillAndStroke(), com.mxgraph.mxICanvas2D.FillColor, com.mxgraph.mxICanvas2D.FixDash, com.mxgraph.mxICanvas2D.FontBackgroundColor, com.mxgraph.mxICanvas2D.FontBorderColor, com.mxgraph.mxICanvas2D.FontColor, com.mxgraph.mxICanvas2D.FontFamily, com.mxgraph.mxICanvas2D.FontSize, com.mxgraph.mxICanvas2D.FontStyle, com.mxgraph.mxICanvas2D.Image(), com.mxgraph.mxICanvas2D.LineCap, com.mxgraph.mxICanvas2D.LineJoin, com.mxgraph.mxICanvas2D.LineTo(), com.mxgraph.mxICanvas2D.MiterLimit, com.mxgraph.mxICanvas2D.MoveTo(), com.mxgraph.mxICanvas2D.QuadTo(), com.mxgraph.mxICanvas2D.Rect(), com.mxgraph.mxICanvas2D.Restore(), com.mxgraph.mxICanvas2D.Rotate(), com.mxgraph.mxICanvas2D.Roundrect(), com.mxgraph.mxICanvas2D.Save(), com.mxgraph.mxICanvas2D.Scale(), com.mxgraph.mxICanvas2D.SetGradient(), com.mxgraph.mxICanvas2D.SetShadowOffset(), com.mxgraph.mxICanvas2D.Shadow, com.mxgraph.mxICanvas2D.ShadowAlpha, com.mxgraph.mxICanvas2D.ShadowColor, com.mxgraph.mxICanvas2D.Stroke(), com.mxgraph.mxICanvas2D.StrokeAlpha, com.mxgraph.mxICanvas2D.StrokeColor, com.mxgraph.mxICanvas2D.StrokeWidth, com.mxgraph.mxICanvas2D.Text(), and com.mxgraph.mxICanvas2D.Translate().
ParseElement()
void com.mxgraph.mxSaxOutputHandler.ParseElement (string tagName, Dictionary< string, string > atts) inline
Parses the given element and paints it onto the canvas.
Parameters
tagName Name of the node to be parsed.
attrs Attributes of the node to be parsed.
Read()
void com.mxgraph.mxSaxOutputHandler.Read (XmlReader reader) inline
Reads the given display XML data and parses all elements.
Parameters
reader Reader that represents the display XML data.
Member Data Documentation
canvas
mxICanvas2D com.mxgraph.mxSaxOutputHandler.canvas protected
Holds the current canvas.
handlers
Dictionary<string, ElementHandler> com.mxgraph.mxSaxOutputHandler.handlers = new Dictionary<string, ElementHandler>() protected
Holds the handlers for specific XML nodes.
Property Documentation
Canvas
mxICanvas2D com.mxgraph.mxSaxOutputHandler.Canvas get set
Sets or returns the current canvas.
The documentation for this class was generated from the following file:
src/reader/mxSaxOutputHandler.cs