mxGraph: com.mxgraph.mxICell Interface Reference
com.mxgraph.mxICell Interface Reference
Defines the requirements for a cell that can be used in an mxGraphModel.
Public Member Functions
mxICell GetTerminal (bool source)
Returns the source or target terminal of the cell.
mxICell SetTerminal (mxICell terminal, bool source)
Sets the source or target terminal.
int ChildCount ()
Returns the number of child cells.
int GetIndex (mxICell child)
Returns the index of the specified child in the child array.
mxICell GetChildAt (int index)
Returns the child at the specified index.
mxICell Insert (mxICell child)
Appends the specified child into the child array and updates the parent reference of the child.
mxICell Insert (mxICell child, int index)
Inserts the specified child into the child array at the specified index and updates the parent reference of the child.
mxICell Remove (int index)
Removes the child at the specified index from the child array and returns the child that was removed. Will remove the parent reference of the child.
mxICell Remove (mxICell child)
Removes the given child from the child array. Will remove the parent reference of the child.
void RemoveFromParent ()
Removes the cell from its parent.
int EdgeCount ()
Returns the number of edges in the edge array.
int GetEdgeIndex (mxICell edge)
Returns the index of the specified edge in the edge array.
mxICell GetEdgeAt (int index)
Returns the edge at the specified index in the edge array.
mxICell InsertEdge (mxICell edge, bool isOutgoing)
Inserts the specified edge into the edge array and returns the edge. Will update the respective terminal reference of the edge.
mxICell RemoveEdge (mxICell edge, bool isOutgoing)
Removes the specified edge from the edge array and returns the edge. Will remove the respective terminal reference from the edge.
void RemoveFromTerminal (bool isSource)
Removes the edge from its source or target terminal.
Object Clone ()
Returns a clone of this cell.
Properties
string Id [get, set]
Sets or returns the Id of the cell.
Object Value [get, set]
Sets or returns the user object of the cell.
mxGeometry Geometry [get, set]
Sets or returns the geometry of the cell.
string Style [get, set]
Sets or returns the string that describes the style.
bool Vertex [get]
Returns true if the cell is a vertex.
bool Edge [get]
Returns true if the cell is an edge.
bool Connectable [get]
Returns true if the cell is connectable.
bool Visible [get, set]
Sets or returns the visible state of the cell.
bool Collapsed [get, set]
Sets or returns the collapsed state of the cell.
mxICell Parent [get, set]
Sets or returns the parent of the cell.
Detailed Description
Defines the requirements for a cell that can be used in an mxGraphModel.
Member Function Documentation
ChildCount()
int com.mxgraph.mxICell.ChildCount ()
Returns the number of child cells.
Returns
Returns the number of child cells.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxGraphModel.CellAdded(), com.mxgraph.mxGraphModel.CellRemoved(), com.mxgraph.mxCodec.EncodeCell(), and com.mxgraph.mxGraphModel.MergeChildrenImpl().
Clone()
Object com.mxgraph.mxICell.Clone ()
Returns a clone of this cell.
Returns
Returns a clone of this cell.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxGraphModel.MergeChildrenImpl().
EdgeCount()
int com.mxgraph.mxICell.EdgeCount ()
Returns the number of edges in the edge array.
Returns
Returns the number of edges.
Implemented in com.mxgraph.mxCell.
GetChildAt()
mxICell com.mxgraph.mxICell.GetChildAt (int index)
Returns the child at the specified index.
Parameters
index Integer that specifies the child to be returned.
Returns
Returns the child at the specified index.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxGraphModel.CellAdded(), com.mxgraph.mxGraphModel.CellRemoved(), com.mxgraph.mxCodec.EncodeCell(), com.mxgraph.mxGraphModel.MergeChildrenImpl(), and com.mxgraph.mxCellPath.Resolve().
GetEdgeAt()
mxICell com.mxgraph.mxICell.GetEdgeAt (int index)
Returns the edge at the specified index in the edge array.
Parameters
index Integer that specifies the index of the edge to be returned.
Returns
Returns the edge at the specified index.
Implemented in com.mxgraph.mxCell.
GetEdgeIndex()
int com.mxgraph.mxICell.GetEdgeIndex (mxICell edge)
Returns the index of the specified edge in the edge array.
Parameters
edge Cell whose index should be returned.
Returns
Returns the index of the given edge.
Implemented in com.mxgraph.mxCell.
GetIndex()
int com.mxgraph.mxICell.GetIndex (mxICell child)
Returns the index of the specified child in the child array.
Parameters
child Child whose index should be returned.
Returns
Returns the index of the specified child.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCellPath.Create().
GetTerminal()
mxICell com.mxgraph.mxICell.GetTerminal (bool source)
Returns the source or target terminal of the cell.
Parameters
source Boolean that specifies if the source terminal should be returned.
Returns
Returns the source or target terminal.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCell.InsertEdge(), com.mxgraph.mxCodec.InsertIntoGraph(), com.mxgraph.mxCell.RemoveEdge(), and com.mxgraph.mxGraphModel.SetTerminal().
Insert() [1/2]
mxICell com.mxgraph.mxICell.Insert (mxICell child)
Appends the specified child into the child array and updates the parent reference of the child.
Parameters
child Cell to be appended to the child array.
Returns
Returns the appended child.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxGraphModel.CloneCell(), com.mxgraph.mxCell.Insert(), com.mxgraph.mxCodec.InsertIntoGraph(), and com.mxgraph.mxGraphModel.MergeChildrenImpl().
Insert() [2/2]
mxICell com.mxgraph.mxICell.Insert (mxICell child, int index)
Inserts the specified child into the child array at the specified index and updates the parent reference of the child.
Parameters
child Cell to be inserted into the child array.
index Integer that specifies the index at which the child should be inserted into the child array.
Returns
Returns the inserted child.
Implemented in com.mxgraph.mxCell.
InsertEdge()
mxICell com.mxgraph.mxICell.InsertEdge (mxICell edge, bool isOutgoing)
Inserts the specified edge into the edge array and returns the edge. Will update the respective terminal reference of the edge.
Parameters
edge Cell to be inserted into the edge array.
isOutgoing Boolean that specifies if the edge is outgoing.
Returns
Returns the inserted edge.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCodec.InsertIntoGraph(), and com.mxgraph.mxGraphModel.RestoreClone().
Remove() [1/2]
mxICell com.mxgraph.mxICell.Remove (int index)
Removes the child at the specified index from the child array and returns the child that was removed. Will remove the parent reference of the child.
Parameters
index Integer that specifies the index of the child to be removed.
Returns
Returns the child that was removed.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCell.Remove(), com.mxgraph.mxCell.RemoveEdge(), and com.mxgraph.mxCell.RemoveFromParent().
Remove() [2/2]
mxICell com.mxgraph.mxICell.Remove (mxICell child)
Removes the given child from the child array. Will remove the parent reference of the child.
Parameters
child
Returns
Returns the child that was removed.
Implemented in com.mxgraph.mxCell.
RemoveEdge()
mxICell com.mxgraph.mxICell.RemoveEdge (mxICell edge, bool isOutgoing)
Removes the specified edge from the edge array and returns the edge. Will remove the respective terminal reference from the edge.
Parameters
edge Cell to be removed from the edge array.
isOutgoing Boolean that specifies if the edge is outgoing.
Returns
Returns the edge that was removed.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCell.RemoveFromTerminal(), and com.mxgraph.mxGraphModel.SetTerminal().
RemoveFromParent()
void com.mxgraph.mxICell.RemoveFromParent ()
Removes the cell from its parent.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCell.Insert(), and com.mxgraph.mxGraphModel.Remove().
RemoveFromTerminal()
void com.mxgraph.mxICell.RemoveFromTerminal (bool isSource)
Removes the edge from its source or target terminal.
Parameters
isSource Boolean that specifies if the edge should be removed from its source or target terminal.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxGraphModel.CellRemoved(), and com.mxgraph.mxCell.InsertEdge().
SetTerminal()
mxICell com.mxgraph.mxICell.SetTerminal (mxICell terminal, bool source)
Sets the source or target terminal.
Parameters
terminal Cell that represents the new source or target terminal.
source Boolean that specifies if the source or target terminal should be set.
Returns
Returns the new terminal.
Implemented in com.mxgraph.mxCell.
Referenced by com.mxgraph.mxCell.InsertEdge(), com.mxgraph.mxCodec.InsertIntoGraph(), and com.mxgraph.mxCell.RemoveEdge().
Property Documentation
Collapsed
bool com.mxgraph.mxICell.Collapsed get set
Sets or returns the collapsed state of the cell.
Connectable
bool com.mxgraph.mxICell.Connectable get
Returns true if the cell is connectable.
Edge
bool com.mxgraph.mxICell.Edge get
Returns true if the cell is an edge.
Geometry
mxGeometry com.mxgraph.mxICell.Geometry get set
Sets or returns the geometry of the cell.
Id
string com.mxgraph.mxICell.Id get set
Sets or returns the Id of the cell.
Referenced by com.mxgraph.mxGraphModel.CellAdded(), com.mxgraph.mxGraphModel.CellRemoved(), and com.mxgraph.mxGraphModel.MergeChildrenImpl().
Parent
mxICell com.mxgraph.mxICell.Parent get set
Sets or returns the parent of the cell.
Referenced by com.mxgraph.mxModelCodec.BeforeDecode(), com.mxgraph.mxCellPath.Create(), com.mxgraph.mxCell.Insert(), com.mxgraph.mxCodec.InsertIntoGraph(), and com.mxgraph.mxCell.Remove().
Style
string com.mxgraph.mxICell.Style get set
Sets or returns the string that describes the style.
Value
Object com.mxgraph.mxICell.Value get set
Sets or returns the user object of the cell.
Vertex
bool com.mxgraph.mxICell.Vertex get
Returns true if the cell is a vertex.
Visible
bool com.mxgraph.mxICell.Visible get set
Sets or returns the visible state of the cell.
The documentation for this interface was generated from the following file:
src/model/mxICell.cs