mxGraph: com.mxgraph.mxICanvas Interface Reference
com.mxgraph.mxICanvas Interface Reference
Defines the requirements for a canvas that paints the vertices and edges of a graph.
Public Member Functions
Object DrawCell (mxCellState state)
Draws the given cell.
Object DrawLabel (string text, mxCellState state, bool html)
Draws the given label.
Properties
Point Translate [get, set]
Sets or returns the user object of the cell.
double Scale [get, set]
Sets or returns the user object of the cell.
Detailed Description
Defines the requirements for a canvas that paints the vertices and edges of a graph.
Member Function Documentation
DrawCell()
Object com.mxgraph.mxICanvas.DrawCell (mxCellState state)
Draws the given cell.
Parameters
state State of the cell to be painted.
Returns
Object that represents the vertex.
Implemented in com.mxgraph.mxImageCanvas, com.mxgraph.mxGdiCanvas, and com.mxgraph.mxBasicCanvas.
Referenced by com.mxgraph.mxGraph.DrawState(), and com.mxgraph.mxGraphViewReader.ParseElement().
DrawLabel()
Object com.mxgraph.mxICanvas.DrawLabel (string text, mxCellState state, bool html)
Draws the given label.
Parameters
text String that represents the label.
state State of the cell whose label is to be painted.
html Specifies if the label contains HTML markup.
Returns
Object that represents the label.
Implemented in com.mxgraph.mxGdiCanvas, com.mxgraph.mxImageCanvas, and com.mxgraph.mxBasicCanvas.
Referenced by com.mxgraph.mxGraph.DrawState(), and com.mxgraph.mxGraphViewReader.ParseElement().
Property Documentation
Scale
double com.mxgraph.mxICanvas.Scale get set
Sets or returns the user object of the cell.
Referenced by com.mxgraph.mxCellRenderer.DrawCells(), and com.mxgraph.mxGraphViewReader.ParseElement().
Translate
Point com.mxgraph.mxICanvas.Translate get set
Sets or returns the user object of the cell.
Referenced by com.mxgraph.mxCellRenderer.DrawCells(), and com.mxgraph.mxGraph.DrawState().
The documentation for this interface was generated from the following file:
src/canvas/mxICanvas.cs