mxGraph: com.mxgraph.mxICanvas2D Interface Reference
com.mxgraph.mxICanvas2D Interface Reference
Defines the requirements for a canvas that paints the vertices and edges of a graph.
Public Member Functions
void Save ()
Saves the current state of the canvas.
void Restore ()
Restores the previous state of the canvas.
void Scale (double value)
Uniformaly scales the canvas by the given amount.
void Translate (double dx, double dy)
Translates the canvas by the given amount.
void Rotate (double theta, bool flipH, bool flipV, double cx, double cy)
Rotates the canvas by the given angle around the given center. This method may add rendering overhead and should be used with care.
void SetGradient (string color1, string color2, double x, double y, double w, double h, string direction, double alpha1, double alpha2)
Prepares the canvas to draw a gradient.
void SetShadowOffset (double dx, double dy)
Prepares the canvas to draw a gradient.
void Rect (double x, double y, double w, double h)
Next fill or stroke should draw a rectangle.
void Roundrect (double x, double y, double w, double h, double dx, double dy)
Next fill or stroke should draw a round rectangle.
void Ellipse (double x, double y, double w, double h)
Next fill or stroke should draw an ellipse.
void Image (double x, double y, double w, double h, string src, bool aspect, bool flipH, bool flipV)
Draws the given image.
void Text (double x, double y, double w, double h, string str, string align, string valign, bool wrap, string format, string overflow, bool clip, double rotation, string dir)
Draws the given string. Possible values for format are empty string for
void Begin ()
Begins a new path.
void MoveTo (double x, double y)
Moves to the given path.
void LineTo (double x, double y)
Draws a line to the given path.
void QuadTo (double x1, double y1, double x2, double y2)
Draws a quadratic curve to the given point.
void CurveTo (double x1, double y1, double x2, double y2, double x3, double y3)
Draws a bezier curve to the given point.
void Close ()
Closes the current path.
void Stroke ()
Paints the outline of the current path.
void Fill ()
Fills the current path.
void FillAndStroke ()
Fills and paints the outline of the current path.
Properties
double StrokeWidth [set]
Sets the stroke width. This should default to 1 if unset.
string StrokeColor [set]
Sets the stroke color. This should default to mxConstants.NONE if unset.
bool Dashed [set]
Sets the dashed state. This should default to false if unset.
bool FixDash [set]
Sets the dashed state. This should default to false if unset.
string DashPattern [set]
Sets the dash pattern. This should default to "3 3" if unset.
string LineCap [set]
Sets the linecap. This should default to "flat" if unset.
string LineJoin [set]
Sets the linejoin. This should default to "miter" if unset.
double MiterLimit [set]
Sets the miterlimit. This should default to 10 if unset.
double FontSize [set]
Default value mxConstants.DEFAULT_FONTSIZE.
string FontColor [set]
Default value "#000000".
string FontFamily [set]
Default value mxConstants#DEFAULT_FONTFAMILY.
int FontStyle [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontBackgroundColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
string FontBorderColor [set]
Default value 0. See mxConstants#STYLE_FONTSTYLE.
double Alpha [set]
Default value 1. This method may add rendering overhead and should be used with care.
double FillAlpha [set]
Default value 1.
double StrokeAlpha [set]
Default value 1.
string FillColor [set]
Default value mxConstants#NONE.
bool Shadow [set]
Default value mxConstants#NONE.
string ShadowColor [set]
Default value mxConstants#NONE.
double ShadowAlpha [set]
Default value 1. This method may add rendering overhead and should be used with care.
Detailed Description
Defines the requirements for a canvas that paints the vertices and edges of a graph.
Member Function Documentation
Begin()
void com.mxgraph.mxICanvas2D.Begin ()
Begins a new path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Close()
void com.mxgraph.mxICanvas2D.Close ()
Closes the current path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
CurveTo()
void com.mxgraph.mxICanvas2D.CurveTo (double x1, double y1, double x2, double y2, double x3, double y3)
Draws a bezier curve to the given point.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Ellipse()
void com.mxgraph.mxICanvas2D.Ellipse (double x, double y, double w, double h)
Next fill or stroke should draw an ellipse.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Fill()
void com.mxgraph.mxICanvas2D.Fill ()
Fills the current path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FillAndStroke()
void com.mxgraph.mxICanvas2D.FillAndStroke ()
Fills and paints the outline of the current path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Image()
void com.mxgraph.mxICanvas2D.Image (double x, double y, double w, double h, string src, bool aspect, bool flipH, bool flipV)
Draws the given image.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
LineTo()
void com.mxgraph.mxICanvas2D.LineTo (double x, double y)
Draws a line to the given path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
MoveTo()
void com.mxgraph.mxICanvas2D.MoveTo (double x, double y)
Moves to the given path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
QuadTo()
void com.mxgraph.mxICanvas2D.QuadTo (double x1, double y1, double x2, double y2)
Draws a quadratic curve to the given point.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Rect()
void com.mxgraph.mxICanvas2D.Rect (double x, double y, double w, double h)
Next fill or stroke should draw a rectangle.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Restore()
void com.mxgraph.mxICanvas2D.Restore ()
Restores the previous state of the canvas.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Rotate()
void com.mxgraph.mxICanvas2D.Rotate (double theta, bool flipH, bool flipV, double cx, double cy)
Rotates the canvas by the given angle around the given center. This method may add rendering overhead and should be used with care.
Parameters
theta Rotation angle in degrees (0 - 360).
flipH Specifies if drawing should be flipped horizontally.
flipV Specifies if drawing should be flipped vertically.
cx X-coordinate of the center point.
cy Y-coordinate of the center point.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Roundrect()
void com.mxgraph.mxICanvas2D.Roundrect (double x, double y, double w, double h, double dx, double dy)
Next fill or stroke should draw a round rectangle.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Save()
void com.mxgraph.mxICanvas2D.Save ()
Saves the current state of the canvas.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Scale()
void com.mxgraph.mxICanvas2D.Scale (double value)
Uniformaly scales the canvas by the given amount.
Parameters
value The new scale value.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
SetGradient()
void com.mxgraph.mxICanvas2D.SetGradient (string color1, string color2, double x, double y, double w, double h, string direction, double alpha1, double alpha2)
Prepares the canvas to draw a gradient.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
SetShadowOffset()
void com.mxgraph.mxICanvas2D.SetShadowOffset (double dx, double dy)
Prepares the canvas to draw a gradient.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Stroke()
void com.mxgraph.mxICanvas2D.Stroke ()
Paints the outline of the current path.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Text()
void com.mxgraph.mxICanvas2D.Text (double x, double y, double w, double h, string str, string align, string valign, bool wrap, string format, string overflow, bool clip, double rotation, string dir)
Draws the given string. Possible values for format are empty string for
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Translate()
void com.mxgraph.mxICanvas2D.Translate (double dx, double dy)
Translates the canvas by the given amount.
Parameters
dx X-coordinate of the translation.
dy Y-coordinate of the translation.
Implemented in com.mxgraph.mxGdiCanvas2D.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Property Documentation
Alpha
double com.mxgraph.mxICanvas2D.Alpha set
Default value 1. This method may add rendering overhead and should be used with care.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Dashed
bool com.mxgraph.mxICanvas2D.Dashed set
Sets the dashed state. This should default to false if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
DashPattern
string com.mxgraph.mxICanvas2D.DashPattern set
Sets the dash pattern. This should default to "3 3" if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FillAlpha
double com.mxgraph.mxICanvas2D.FillAlpha set
Default value 1.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FillColor
string com.mxgraph.mxICanvas2D.FillColor set
Default value mxConstants#NONE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FixDash
bool com.mxgraph.mxICanvas2D.FixDash set
Sets the dashed state. This should default to false if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontBackgroundColor
string com.mxgraph.mxICanvas2D.FontBackgroundColor set
Default value 0. See mxConstants#STYLE_FONTSTYLE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontBorderColor
string com.mxgraph.mxICanvas2D.FontBorderColor set
Default value 0. See mxConstants#STYLE_FONTSTYLE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontColor
string com.mxgraph.mxICanvas2D.FontColor set
Default value "#000000".
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontFamily
string com.mxgraph.mxICanvas2D.FontFamily set
Default value mxConstants#DEFAULT_FONTFAMILY.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontSize
double com.mxgraph.mxICanvas2D.FontSize set
Default value mxConstants.DEFAULT_FONTSIZE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
FontStyle
int com.mxgraph.mxICanvas2D.FontStyle set
Default value 0. See mxConstants#STYLE_FONTSTYLE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
LineCap
string com.mxgraph.mxICanvas2D.LineCap set
Sets the linecap. This should default to "flat" if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
LineJoin
string com.mxgraph.mxICanvas2D.LineJoin set
Sets the linejoin. This should default to "miter" if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
MiterLimit
double com.mxgraph.mxICanvas2D.MiterLimit set
Sets the miterlimit. This should default to 10 if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
Shadow
bool com.mxgraph.mxICanvas2D.Shadow set
Default value mxConstants#NONE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
ShadowAlpha
double com.mxgraph.mxICanvas2D.ShadowAlpha set
Default value 1. This method may add rendering overhead and should be used with care.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
ShadowColor
string com.mxgraph.mxICanvas2D.ShadowColor set
Default value mxConstants#NONE.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
StrokeAlpha
double com.mxgraph.mxICanvas2D.StrokeAlpha set
Default value 1.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
StrokeColor
string com.mxgraph.mxICanvas2D.StrokeColor set
Sets the stroke color. This should default to mxConstants.NONE if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
StrokeWidth
double com.mxgraph.mxICanvas2D.StrokeWidth set
Sets the stroke width. This should default to 1 if unset.
Referenced by com.mxgraph.mxSaxOutputHandler.InitHandlers().
The documentation for this interface was generated from the following file:
src/canvas/mxICanvas2D.cs