mxGraph: com.mxgraph.mxIGraphModel Interface Reference
com.mxgraph.mxIGraphModel Interface Reference
Defines the requirements for a graph model to be used with mxGraph.
Public Member Functions
Object [] CloneCells (Object[] cells, bool includeChildren)
Returns an array of clones for the given array of cells. Depending on the value of includeChildren, a deep clone is created for each cell. Connections are restored based if the corresponding cell is contained in the passed in array.
bool IsAncestor (Object parent, Object child)
Returns true if the given parent is an ancestor of child.
bool Contains (Object cell)
Returns true if the model contains the given cell.
Object GetParent (Object child)
Returns the parent of the given cell.
Object Add (Object parent, Object child, int index)
Adds the specified child to the parent at the given index. If no index is specified then the child is appended to the parent's array of children.
Object Remove (Object parent)
Removes the specified cell from the model. This operation will remove the cell and all of its children from the model.
int GetChildCount (Object cell)
Returns the number of children in the given cell.
Object GetChildAt (Object parent, int index)
Returns the child of the given parent at the given index.
Object GetTerminal (Object edge, bool source)
Returns the source or target terminal of the given edge depending on the value of the boolean parameter.
Object SetTerminal (Object edge, Object terminal, bool source)
Sets the source or target terminal of the given edge using.
int GetEdgeCount (Object cell)
Returns the number of distinct edges connected to the given cell.
Object GetEdgeAt (Object cell, int index)
Returns the edge of cell at the given index.
bool IsVertex (Object cell)
Returns true if the given cell is a vertex.
bool IsEdge (Object cell)
Returns true if the given cell is an edge.
bool IsConnectable (Object cell)
Returns true if the given cell is connectable.
Object GetValue (Object cell)
Returns the user object of the given cell.
Object SetValue (Object cell, Object value)
Sets the user object of then given cell.
mxGeometry GetGeometry (Object cell)
Returns the geometry of the given cell.
mxGeometry SetGeometry (Object cell, mxGeometry geometry)
Sets the geometry of the given cell.
string GetStyle (Object cell)
Returns the style of the given cell.
string SetStyle (Object cell, string style)
Sets the style of the given cell.
bool IsCollapsed (Object cell)
Returns true if the given cell is collapsed.
bool SetCollapsed (Object cell, bool collapsed)
Sets the collapsed state of the given cell.
bool IsVisible (Object cell)
Returns true if the given cell is visible.
bool SetVisible (Object cell, bool visible)
Sets the visible state of the given cell.
void BeginUpdate ()
Increments the updateLevel by one. The event notification is queued until updateLevel reaches 0 by use of endUpdate.
void EndUpdate ()
Decrements the updateLevel by one and fires a notification event if the updateLevel reaches 0.
Properties
Object Root [get, set]
Holds the root cell.
Events
mxGraphModelChangeEventHandler GraphModelChange
Called when the graph model has changed.
Detailed Description
Defines the requirements for a graph model to be used with mxGraph.
Member Function Documentation
Add()
Object com.mxgraph.mxIGraphModel.Add (Object parent, Object child, int index)
Adds the specified child to the parent at the given index. If no index is specified then the child is appended to the parent's array of children.
Parameters
parent Cell that specifies the parent to contain the child.
child Cell that specifies the child to be inserted.
index Integer that specifies the index of the child.
Returns
Returns the inserted child.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.InsertEdge(), and com.mxgraph.mxGraph.InsertVertex().
BeginUpdate()
void com.mxgraph.mxIGraphModel.BeginUpdate ()
Increments the updateLevel by one. The event notification is queued until updateLevel reaches 0 by use of endUpdate.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxFastOrganicLayout.execute(), com.mxgraph.mxGraph.InsertEdge(), com.mxgraph.mxUtils.SetCellStyleFlags(), com.mxgraph.mxUtils.SetCellStyles(), and com.mxgraph.mxGraphModel.SetTerminals().
CloneCells()
Object [] com.mxgraph.mxIGraphModel.CloneCells (Object [] cells, bool includeChildren)
Returns an array of clones for the given array of cells. Depending on the value of includeChildren, a deep clone is created for each cell. Connections are restored based if the corresponding cell is contained in the passed in array.
Parameters
cells Array of cells to be cloned.
includeChildren Boolean indicating if the cells should be cloned with all descendants.
Returns
Returns a cloned array of cells.
Implemented in com.mxgraph.mxGraphModel.
Contains()
bool com.mxgraph.mxIGraphModel.Contains (Object cell)
Returns true if the model contains the given cell.
Parameters
cell Cell to be checked.
Returns
Returns true if the cell is in the model.
Implemented in com.mxgraph.mxGraphModel.
EndUpdate()
void com.mxgraph.mxIGraphModel.EndUpdate ()
Decrements the updateLevel by one and fires a notification event if the updateLevel reaches 0.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxFastOrganicLayout.execute(), com.mxgraph.mxGraph.InsertEdge(), com.mxgraph.mxUtils.SetCellStyleFlags(), com.mxgraph.mxUtils.SetCellStyles(), and com.mxgraph.mxGraphModel.SetTerminals().
GetChildAt()
Object com.mxgraph.mxIGraphModel.GetChildAt (Object parent, int index)
Returns the child of the given parent at the given index.
Parameters
parent Cell that represents the parent.
index Integer that specifies the index of the child to be returned.
Returns
Returns the child at index in parent.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.DrawCell(), com.mxgraph.mxFastOrganicLayout.execute(), com.mxgraph.mxGraph.FindTreeRoots(), com.mxgraph.mxGraphView.GetBoundingBox(), com.mxgraph.mxGraph.GetCellAt(), com.mxgraph.mxGraph.GetCellBounds(), com.mxgraph.mxGraphModel.getChildCells(), com.mxgraph.mxGraph.GetDefaultParent(), com.mxgraph.mxGraph.GetEdges(), com.mxgraph.mxGraphView.RemoveState(), com.mxgraph.mxGraphView.ValidateCell(), and com.mxgraph.mxGraphView.ValidateCellState().
GetChildCount()
int com.mxgraph.mxIGraphModel.GetChildCount (Object cell)
Returns the number of children in the given cell.
Parameters
cell Cell whose number of children should be returned.
Returns
Returns the number of children in the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.DrawCell(), com.mxgraph.mxFastOrganicLayout.execute(), com.mxgraph.mxGraph.FindTreeRoots(), com.mxgraph.mxGraphView.GetBoundingBox(), com.mxgraph.mxGraph.GetCellAt(), com.mxgraph.mxGraph.GetCellBounds(), com.mxgraph.mxGraphModel.getChildCells(), com.mxgraph.mxGraph.GetEdges(), com.mxgraph.mxGraph.InsertEdge(), com.mxgraph.mxGraph.InsertVertex(), com.mxgraph.mxGraphView.RemoveState(), com.mxgraph.mxGraphView.ValidateCell(), and com.mxgraph.mxGraphView.ValidateCellState().
GetEdgeAt()
Object com.mxgraph.mxIGraphModel.GetEdgeAt (Object cell, int index)
Returns the edge of cell at the given index.
Parameters
cell Cell that specifies the vertex.
index Integer that specifies the index of the edge to return.
Returns
Returns the edge at the given index.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.GetCellBounds(), com.mxgraph.mxGraphModel.GetDirectedEdgeCount(), com.mxgraph.mxGraphModel.GetEdges(), and com.mxgraph.mxGraphModel.GetEdgesBetween().
GetEdgeCount()
int com.mxgraph.mxIGraphModel.GetEdgeCount (Object cell)
Returns the number of distinct edges connected to the given cell.
Parameters
cell Cell that represents the vertex.
Returns
Returns the number of edges connected to cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.GetCellBounds(), com.mxgraph.mxGraphModel.GetDirectedEdgeCount(), com.mxgraph.mxGraphModel.GetEdges(), com.mxgraph.mxGraphModel.GetEdgesBetween(), and com.mxgraph.mxFastOrganicLayout.IsCellIgnored().
GetGeometry()
mxGeometry com.mxgraph.mxIGraphModel.GetGeometry (Object cell)
Returns the geometry of the given cell.
Parameters
cell Cell whose geometry should be returned.
Returns
Returns the geometry of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxFastOrganicLayout.execute(), and com.mxgraph.mxGraph.GetCellGeometry().
GetParent()
Object com.mxgraph.mxIGraphModel.GetParent (Object child)
Returns the parent of the given cell.
Parameters
child Cell whose parent should be returned.
Returns
Returns the parent of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraphView.GetVisibleTerminal(), com.mxgraph.mxGraph.IsValidAncestor(), com.mxgraph.mxGraphView.UpdateCellState(), and com.mxgraph.mxGraphView.ValidateCellState().
GetStyle()
string com.mxgraph.mxIGraphModel.GetStyle (Object cell)
Returns the style of the given cell.
Parameters
cell Cell whose style should be returned.
Returns
Returns the style of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.GetCellStyle(), com.mxgraph.mxUtils.SetCellStyleFlags(), and com.mxgraph.mxUtils.SetCellStyles().
GetTerminal()
Object com.mxgraph.mxIGraphModel.GetTerminal (Object edge, bool source)
Returns the source or target terminal of the given edge depending on the value of the boolean parameter.
Parameters
edge Cell that specifies the edge.
source Boolean indicating which end of the edge should be returned.
Returns
Returns the source or target of the given edge.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraphModel.GetDirectedEdgeCount(), com.mxgraph.mxGraphModel.GetEdges(), com.mxgraph.mxGraphModel.GetEdgesBetween(), com.mxgraph.mxGraphModel.GetOpposites(), com.mxgraph.mxGraphView.GetVisibleTerminal(), and com.mxgraph.mxGraphView.UpdateEdgeState().
GetValue()
Object com.mxgraph.mxIGraphModel.GetValue (Object cell)
Returns the user object of the given cell.
Parameters
cell Cell whose user object should be returned.
Returns
Returns the user object of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.ConvertValueToString().
IsAncestor()
bool com.mxgraph.mxIGraphModel.IsAncestor (Object parent, Object child)
Returns true if the given parent is an ancestor of child.
Parameters
parent Cell that specifies the parent.
child Cell that specifies the child.
Returns
Returns true if child is an ancestor of parent.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.IsValidAncestor().
IsCollapsed()
bool com.mxgraph.mxIGraphModel.IsCollapsed (Object cell)
Returns true if the given cell is collapsed.
Parameters
cell Cell whose collapsed state should be returned.
Returns
Returns the collapsed state of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.IsCellCollapsed().
IsConnectable()
bool com.mxgraph.mxIGraphModel.IsConnectable (Object cell)
Returns true if the given cell is connectable.
Parameters
cell Cell whose connectable state should be returned.
Returns
Returns the connectable state of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.IsCellConnectable().
IsEdge()
bool com.mxgraph.mxIGraphModel.IsEdge (Object cell)
Returns true if the given cell is an edge.
Parameters
cell Cell that represents the possible edge.
Returns
Returns true if the given cell is an edge.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.DrawState(), com.mxgraph.mxGraphView.GetBounds(), com.mxgraph.mxGraph.GetCellStyle(), com.mxgraph.mxGraphModel.getChildCells(), com.mxgraph.mxGraphView.UpdateBoundingBox(), com.mxgraph.mxGraphView.UpdateCellState(), com.mxgraph.mxGraphView.UpdateLabelBounds(), and com.mxgraph.mxGraphView.ValidateCellState().
IsVertex()
bool com.mxgraph.mxIGraphModel.IsVertex (Object cell)
Returns true if the given cell is a vertex.
Parameters
cell Cell that represents the possible vertex.
Returns
Returns true if the given cell is a vertex.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.DrawState(), com.mxgraph.mxGraph.FindTreeRoots(), com.mxgraph.mxGraphView.GetBounds(), com.mxgraph.mxGraphModel.getChildCells(), com.mxgraph.mxFastOrganicLayout.IsCellIgnored(), com.mxgraph.mxGraphView.UpdateCellState(), and com.mxgraph.mxGraphView.ValidateCellState().
IsVisible()
bool com.mxgraph.mxIGraphModel.IsVisible (Object cell)
Returns true if the given cell is visible.
Parameters
cell Cell whose visible state should be returned.
Returns
Returns the visible state of the given cell.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.IsCellVisible().
Remove()
Object com.mxgraph.mxIGraphModel.Remove (Object parent)
Removes the specified cell from the model. This operation will remove the cell and all of its children from the model.
Parameters
parent Cell that should be removed.
Returns
Returns the removed cell.
Implemented in com.mxgraph.mxGraphModel.
SetCollapsed()
bool com.mxgraph.mxIGraphModel.SetCollapsed (Object cell, bool collapsed)
Sets the collapsed state of the given cell.
Parameters
cell Cell whose collapsed state should be changed.
collapsed Boolean that specifies the new collpased state.
Implemented in com.mxgraph.mxGraphModel.
SetGeometry()
mxGeometry com.mxgraph.mxIGraphModel.SetGeometry (Object cell, mxGeometry geometry)
Sets the geometry of the given cell.
Parameters
cell Cell whose geometry should be changed.
geometry Object that defines the new geometry.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxFastOrganicLayout.execute().
SetStyle()
string com.mxgraph.mxIGraphModel.SetStyle (Object cell, string style)
Sets the style of the given cell.
Parameters
cell Cell whose style should be changed.
style String of the form stylename[;key=value] to specify the new cell style.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxUtils.SetCellStyleFlags(), and com.mxgraph.mxUtils.SetCellStyles().
SetTerminal()
Object com.mxgraph.mxIGraphModel.SetTerminal (Object edge, Object terminal, bool source)
Sets the source or target terminal of the given edge using.
Parameters
edge Cell that specifies the edge.
terminal Cell that specifies the new terminal.
source Boolean indicating if the terminal is the new source or target terminal of the edge.
Implemented in com.mxgraph.mxGraphModel.
Referenced by com.mxgraph.mxGraph.InsertEdge(), and com.mxgraph.mxGraphModel.SetTerminals().
SetValue()
Object com.mxgraph.mxIGraphModel.SetValue (Object cell, Object value)
Sets the user object of then given cell.
Parameters
cell Cell whose user object should be changed.
value Object that defines the new user object.
Implemented in com.mxgraph.mxGraphModel.
SetVisible()
bool com.mxgraph.mxIGraphModel.SetVisible (Object cell, bool visible)
Sets the visible state of the given cell.
Parameters
cell Cell whose visible state should be changed.
visible Boolean that specifies the new visible state.
Implemented in com.mxgraph.mxGraphModel.
Property Documentation
Root
Object com.mxgraph.mxIGraphModel.Root get set
Holds the root cell.
Referenced by com.mxgraph.mxCellRenderer.DrawCells(), com.mxgraph.mxGraph.DrawGraph(), com.mxgraph.mxGraph.DrawState(), com.mxgraph.mxGraph.GetDefaultParent(), com.mxgraph.mxGraphView.GetVisibleTerminal(), and com.mxgraph.mxGraphView.Validate().
Event Documentation
GraphModelChange
mxGraphModelChangeEventHandler com.mxgraph.mxIGraphModel.GraphModelChange
Called when the graph model has changed.
The documentation for this interface was generated from the following file:
src/model/mxIGraphModel.cs