mxGraph: com.mxgraph Namespace Reference
com.mxgraph Namespace Reference
Classes
class mxBasicCanvas
Basic implementation of a canvas that draws a graph.
class mxCell
Cells are the elements of the graph model. They represent the state of the groups, vertices and edges in a graph.
class mxCellCodec
Codec for mxCells. This class is created and registered dynamically at load time and used implicitely via mxCodec and the mxCodecRegistry.
class mxCellPath
Implements a mechanism for temporary cell Ids.
class mxCellRenderer
Class that can draw an independent array of cells.
class mxCellState
Represents the current state of a cell in a given graph view.
class mxCodec
XML codec for .NET object graphs. In order to resolve forward references when reading files the XML document that contains the data must be passed to the constructor. Here is an example for parsing an existing XML document into a graph model:
class mxCodecRegistry
Static class that acts as a global registry for codecs. See mxCodec for an example of using this class.
class mxConnectionConstraint
Defines an object that contains the constraints about how to connect one side of an edge to its terminal.
class mxConstants
Defines various global constants.
class mxEdgeStyle
Provides various edge styles to be used as the values for mxConstants.STYLE_EDGE in a cell style.
class mxFastOrganicLayout
Fast organic layout algorithm.
class mxGdiCanvas
Implementation of a canvas that uses GDI for painting.
class mxGdiCanvas2D
Used for exporting images. To render to an image from a given XML string, graph size and and background color, the following code is used:
class mxGeometry
Represents the geometry of a cell. For vertices, the geometry consists of the x- and y-location, as well as the width and height. For edges, the edge either defines the source- and target-terminal, or the geometry defines the respective terminal points.
class mxGraph
Implements a graph object that allows to create diagrams from a graph model and stylesheet.
class mxGraphModel
Implements a graph model. The graph model acts as a wrapper around the cells which are in charge of storing the actual graph datastructure. The model acts as a transactional wrapper with event notification for all changes, whereas the cells contain the atomic operations for updating the actual datastructure.
class mxGraphView
Implements a view for the graph. This class is in charge of computing the absolute coordinates for the relative child geometries, the points for perimeters and edge styles and keeping them cached in mxCellStates for faster retrieval. The states are updated whenever the model or the view state (translate, scale) changes. The scale and translate are honoured in the bounds.
class mxGraphViewImageReader
A converter that renders display XML data onto a GDI canvas.
class mxGraphViewReader
An abstract converter that renders display XML data onto a canvas.
interface mxICanvas
Defines the requirements for a canvas that paints the vertices and edges of a graph.
interface mxICanvas2D
Defines the requirements for a canvas that paints the vertices and edges of a graph.
interface mxICell
Defines the requirements for a cell that can be used in an mxGraphModel.
interface mxIGraphLayout
Defines the requirements for an object that implements a graph layout.
interface mxIGraphModel
Defines the requirements for a graph model to be used with mxGraph.
class mxImageBundle
Maps from keys to base64 encoded images or file locations. All values must be URLs or use the format data:image/format followed by a comma and the base64 encoded image data, eg. "data:image/gif,XYZ", where XYZ is the base64 encoded image data.
class mxImageCanvas
Implements a canvas that draws onto an image.
class mxModelCodec
Codec for mxGraphModels. This class is created and registered dynamically at load time and used implicitely via mxCodec and the mxCodecRegistry.
class mxObjectCodec
Generic codec for C# objects. See below for a detailed description of the encoding/decoding scheme. Note: Since booleans are numbers in JavaScript, all boolean values are encoded into 1 for true and 0 for false.
class mxPerimeter
Provides various perimeter functions to be used in a style as the value of mxConstants.STYLE_PERIMETER.
class mxPoint
Implements a 2-dimensional point with double precision coordinates.
class mxRectangle
Implements a 2-dimensional rectangle with double precision coordinates.
class mxSaxOutputHandler
class mxStencil
Implements a stencil for the given XML definition. This class implements the mxGraph stencil schema.
class mxStencilRegistry
class mxStyleRegistry
Static class that acts as a global registry for codecs. See mxCodec for an example of using this class.
class mxStylesheet
Defines the appearance of the cells in a graph.
class mxStylesheetCodec
Codec for mxStylesheets. This class is created and registered dynamically at load time and used implicitely via mxCodec and the mxCodecRegistry.
class mxUtils
Contains various helper methods for use with mxGraph.
Functions
delegate void mxGraphModelChangeEventHandler ()
Defines the requirements for an object that listens to a graph model.
delegate void mxEdgeStyleFunction (mxCellState state, mxCellState source, mxCellState target, List< mxPoint > points, List< mxPoint > result)
Defines the requirements for an edge style function. At the time the function is called, the result array contains a placeholder (null) for the first absolute point, that is, the point where the edge and source terminal are connected. The implementation of the style then adds all intermediate waypoints except for the last point, that is, the connection point between the edge and the target terminal. The first ant the last point in the result array are then replaced with mxPoints that take into account the terminal's perimeter and next point on the edge.
delegate mxPoint mxPerimeterFunction (mxRectangle bounds, mxCellState vertex, mxPoint next, bool orthogonal)
Defines the requirements for a perimeter function.
Function Documentation
mxEdgeStyleFunction()
delegate void com.mxgraph.mxEdgeStyleFunction (mxCellState state, mxCellState source, mxCellState target, List< mxPoint > points, List< mxPoint > result)
Defines the requirements for an edge style function. At the time the function is called, the result array contains a placeholder (null) for the first absolute point, that is, the point where the edge and source terminal are connected. The implementation of the style then adds all intermediate waypoints except for the last point, that is, the connection point between the edge and the target terminal. The first ant the last point in the result array are then replaced with mxPoints that take into account the terminal's perimeter and next point on the edge.
Parameters
state Cell state that represents the edge to be updated.
source Cell state that represents the source terminal.
target Cell state that represents the target terminal.
points List of relative control points.
result Array of points that represent the actual points of the edge.
Referenced by com.mxgraph.mxGraphView.GetEdgeStyle(), com.mxgraph.mxGraph.IsOrthogonal(), and com.mxgraph.mxGraphView.UpdatePoints().
mxGraphModelChangeEventHandler()
delegate void com.mxgraph.mxGraphModelChangeEventHandler ()
Defines the requirements for an object that listens to a graph model.
mxPerimeterFunction()
delegate mxPoint com.mxgraph.mxPerimeterFunction (mxRectangle bounds, mxCellState vertex, mxPoint next, bool orthogonal)
Defines the requirements for a perimeter function.
Parameters
bounds Rectangle that represents the absolute bounds of the vertex.
vertex Cell state that represents the vertex.
next Point that represents the nearest neighbour point on the given edge.
orthogonal Boolean that specifies if the orthogonal projection onto the perimeter should be returned. If this is false then the intersection of the perimeter and the line between the next and the center point is returned.
Referenced by com.mxgraph.mxGraphView.GetPerimeterFunction(), and com.mxgraph.mxGraphView.GetPerimeterPoint().